# -*- coding: utf-8 -*-
"""H3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WqFk3ZytvLs3apOpb417Un5Wl1k3jwIJ

86a901287ffffff, 86a90128fffffff, 86a90129fffffff, 86a90e927ffffff, 86a90e937ffffff, 86a90166fffffff, 86a901297ffffff, 86a9012afffffff, 86a9012a7ffffff, 86a9012b7ffffff, 86a901667ffffff, 86a90174fffffff, 86a90139fffffff, 86a90176fffffff, 86a90e907ffffff, 86a90e92fffffff, 86a9012d7ffffff, 86a90138fffffff, 86a901387ffffff, 86a901397ffffff, 86a901767ffffff, 86a901747ffffff, 86a90175fffffff, 86a901677ffffff, 86a901647ffffff, 86a90164fffffff, 86a90e917ffffff, 86a90e91fffffff, 86a90e90fffffff
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install --upgrade --force-reinstall h3

import h3
import pandas as pd

h3_indexes = [
    "86a901287ffffff","86a90128fffffff","86a90129fffffff",
    "86a90e927ffffff","86a90e937ffffff","86a90166fffffff",
    "86a901297ffffff","86a9012afffffff","86a9012a7ffffff",
    "86a9012b7ffffff","86a901667ffffff","86a90174fffffff",
    "86a90139fffffff","86a90176fffffff","86a90e907ffffff",
    "86a90e92fffffff","86a9012d7ffffff","86a90138fffffff",
    "86a901387ffffff","86a901397ffffff","86a901767ffffff",
    "86a901747ffffff","86a90175fffffff","86a901677ffffff",
    "86a901647ffffff","86a90164fffffff","86a90e917ffffff",
    "86a90e91fffffff","86a90e90fffffff"
]

rows = []
for h in h3_indexes:
    lat, lon = h3.cell_to_latlng(h)
    rows.append({
        "h3": h,
        "lat": lat,
        "lon": lon
    })

df = pd.DataFrame(rows)
df

h3.cell_to_boundary(h)

#df.to_csv('/content/drive/MyDrive/DOUTORADO/DATASETS/DATASETS_PRONTOS/h3_data_filhos_RMPOA.csv', index=False)
#print('CSV file saved to /content/drive/MyDrive/DOUTORADO/DATASETS/h3_data_filhos_RMPOA')

loc = [
    1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
]

weather_df = pd.read_csv('Weather_2025_v4.csv', sep=';')

# Map location_id to h3 using the index of df
weather_df['location'] = weather_df['location_id'].map(df['h3'])

weather_df.head()

import h3
from h3 import LatLngPoly

h3_res5_list = [
"88a90e9359fffff",
"88a90e9265fffff",
"88a90129b3fffff",
"88a90129b7fffff",
"88a90e935dfffff",
"88a90e9343fffff",
"88a90e9347fffff",
"88a90e9341fffff",
"88a90e934bfffff"
]



all_res12 = set()

for h in h3_res5_list:
    boundary = h3.cell_to_boundary(h)
    poly = LatLngPoly(boundary)
    all_res12.update(h3.polygon_to_cells(poly, 12))

len(all_res12)

df_all_res12 = pd.DataFrame(list(all_res12), columns=['h3_index'])
df_all_res12.head()
df_all_res12.to_csv("Aeroporto_Salgado_Filho_h3_res12.csv")

df_all_res12.to_csv('/content/drive/MyDrive/DOUTORADO/DATASETS/DATASETS_PRONTOS/Aeroporto_Salgado_Filho_h3_res12.csv', index=False)