# -*- coding: utf-8 -*-
"""Open-Weather_Data_Collector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1waXxMDKnBExqpIadq1zM6BuRikZsgVrl

# Extração de Dados Meteorológicos (Open-Meteo)

Este notebook tem como objetivo automatizar a extração de dados meteorológicos históricos utilizando a API do [Open-Meteo](https://open-meteo.com/).

## Visão Geral
A partir de uma lista de coordenadas (Latitude e Longitude) e seus respectivos identificadores (como o índice H3), o script irá:
1. Consultar a API do Open-Meteo para um período específico (2025 a 2026).
2. Extrair dezenas de métricas diárias e horárias (como temperatura, precipitação, radiação, velocidade do vento, etc.).
3. Consolidar as informações em um único `DataFrame` do Pandas.
4. Exportar os resultados para um arquivo CSV para análises futuras.

## Passo a Passo do Pipeline de Dados

A célula de código abaixo realiza todas as etapas do processo de forma integrada:
- **Passo 1: Importação de Bibliotecas**: Utilizamos `requests` para chamadas de API web, `pandas` para estruturação dos dados tabulares e `time` para evitar sobrecarga na API.
- **Passo 2: Definição dos Locais**: A variável `locais` armazena as coordenadas que queremos consultar.
- **Passo 3: Construção da URL e Requisição**: Para cada local, montamos a URL com os parâmetros exatos de dados atmosféricos solicitados.
- **Passo 4: Processamento**: Transformamos as respostas JSON em DataFrames individuais.
- **Passo 5: Agregação e Exportação**: Unimos tudo e salvamos no arquivo `dados_meteorologicos.csv`.

*Instrução: Sinta-se livre para modificar a lista de `locais` com as suas coordenadas reais antes de executar a célula.*
"""

from google.colab import drive
drive.mount('/content/drive')

import requests
import pandas as pd
import time

# Array com as informações: [INDEX_H3, LAT, LONG]
# Substitua com seus dados reais
locais = [
    ['85a90e93fffffff', -29.934, -51.189],
    ['85a9012ffffffff', -29.989, -51.341],
    ['85a9012bfffffff', -30.070, -51.195],
    ['85a9013bfffffff', -30.205, -51.200],
    ['85a90177fffffff', -30.150, -51.049],
    ['85a90167fffffff', -30.014, -51.044],
    ['85a90e9bfffffff', -29.879, -51.038],
    ['85a90e83fffffff', -29.798, -51.184],
    ['85a90e87fffffff', -29.717, -51.330],
    ['85a90e97fffffff', -29.853, -51.335],
    ['85a90e8ffffffff', -29.662, -51.178],
    ['85a90e8bfffffff', -29.743, -51.033],
    ['85a90ebbfffffff', -29.581, -51.324]
]

# Lista para armazenar todos os dados diários e horários processados
todos_dados = []

for local in locais:
    index_h3, lat, lon = local

    # Substitua a elevação se necessário
    elevation = 70

    url = f"https://archive-api.open-meteo.com/v1/archive" \
          f"?latitude={lat}&longitude={lon}&elevation={elevation}" \
          f"&start_date=2025-01-01&end_date=2026-01-01" \
          f"&daily=weather_code,temperature_2m_mean,temperature_2m_max,temperature_2m_min,apparent_temperature_mean,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,precipitation_hours,shortwave_radiation_sum,sunshine_duration,daylight_duration,sunrise,sunset,wind_speed_10m_max,wind_gusts_10m_max" \
          f"&hourly=temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,rain,weather_code,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance,sunshine_duration,surface_pressure,pressure_msl,vapour_pressure_deficit" \
          f"&temperature_unit=celsius&wind_speed_unit=ms&precipitation_unit=mm" \
          f"&timezone=America%2FSao_Paulo&timeformat=iso8601&cell_selection=land"

    max_retries = 5
    base_delay = 10

    for attempt in range(max_retries):
        try:
            print(f"Baixando dados para {index_h3} (Tentativa {attempt + 1}/{max_retries})...")
            response = requests.get(url)

            if response.status_code == 429:
                # Exponential backoff: 10s, 20s, 40s, 80s...
                sleep_time = base_delay * (2 ** attempt)
                print(f"Rate limit reached (429). Backing off for {sleep_time} seconds...")
                time.sleep(sleep_time)
                continue

            response.raise_for_status()
            dados_json = response.json()

            # Exemplo de extração dos dados diários
            if 'daily' in dados_json:
                df_daily = pd.DataFrame(dados_json['daily'])
                df_daily['INDEX_H3'] = index_h3
                df_daily['LAT'] = lat
                df_daily['LONG'] = lon
                df_daily['ELEVATION'] = elevation
                todos_dados.append(df_daily)

            # Base delay to prevent overwhelming the API on successful requests
            time.sleep(2)
            break # Break out of the retry loop if successful

        except Exception as e:
            print(f"Erro ao processar {index_h3}: {e}")
            if attempt == max_retries - 1:
                print(f"Skipping {index_h3} after {max_retries} failed attempts.")
            else:
                time.sleep(5) # Small wait before next retry on non-429 errors

# Combina todos os dados em um único DataFrame
if todos_dados:
    df_final = pd.concat(todos_dados, ignore_index=True)

    # Salva em CSV
    nome_arquivo = 'dados_meteorologicos.csv'
    df_final.to_csv(nome_arquivo, index=False)
    print(f"\nDados salvos com sucesso em {nome_arquivo}")

    # Mostra as primeiras linhas do DataFrame final
    display(df_final.head())
else:
    print("Nenhum dado foi obtido.")

import os

# Caminho do diretório de destino no Google Drive
diretorio_destino = '/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base'
caminho_arquivo = f'{diretorio_destino}/dados_meteorologicos.csv'

# Cria o diretório caso ele não exista
os.makedirs(diretorio_destino, exist_ok=True)

# Verifica se o DataFrame df_final existe e o salva no local especificado
if 'df_final' in locals():
    df_final.to_csv(caminho_arquivo, index=False)
    print(f"Arquivo salvo com sucesso em: {caminho_arquivo}")
else:
    print("O DataFrame 'df_final' não foi encontrado. Execute a célula anterior de extração de dados primeiro.")