# -*- coding: utf-8 -*-
"""OSM_TO_H3_EDGES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q1-8MdhN5_N__y1LejdhInAh51oKg8M3
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install osmium

!apt-get update
!apt-get install -y libosmium-dev
!pip install pyosmium h3 pandas tqdm

!pip install h3
import osmium
import h3
import pandas as pd
import shutil

file_path = '/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base/POA.osm.pbf'
destination_path = './' # Copies to the current working directory

shutil.copy(file_path, destination_path)

# Vias trafegáveis
VALID_HIGHWAYS = {
    "motorway", "trunk", "primary", "secondary", "tertiary",
    "unclassified", "residential", "service", "living_street",
    "road", "alley"
}

class RoadExtractor(osmium.SimpleHandler):
    def __init__(self):
        super().__init__()
        self.rows = []

    def way(self, w):
        highway = w.tags.get("highway")
        if highway not in VALID_HIGHWAYS:
            return

        for n in w.nodes:
            if not n.location.valid():
                continue

            lat = n.location.lat
            lon = n.location.lon

            self.rows.append({
                "way_id": w.id,
                "node_id": n.ref,
                "lat": lat,
                "lon": lon,
                "h3_6": h3.latlng_to_cell(lat, lon, 6),
                "h3_8": h3.latlng_to_cell(lat, lon, 8),
                "h3_10": h3.latlng_to_cell(lat, lon, 10),
                "h3_12": h3.latlng_to_cell(lat, lon, 12),
                "h3_13": h3.latlng_to_cell(lat, lon, 13),
                "h3_15": h3.latlng_to_cell(lat, lon, 15),
            })

# Executa o parser
handler = RoadExtractor()
handler.apply_file(
    "POA.osm.pbf",
    locations=True
)

# Converte para DataFrame
df = pd.DataFrame(handler.rows)

# Salva CSV
df.to_csv("vias_trafegaveis_poa_h3.csv", index=False)

print(f"Total de pontos extraídos: {len(df)}")

df = df.sort_values(by='lat', ascending=True)
print(df.head())

df2 = df
#print(df2)
# Bounding box
""" VERSÃO FULL
LAT_MIN = -30.2869
LAT_MAX = -29.6141
LON_MIN = -51.2835
LON_MAX = -50.9409"""

""" VERSÃO POCKET"""
LAT_MIN = -30.0602
LAT_MAX = -30.0219
LON_MIN = -51.2415
LON_MAX = -51.1901

# Filter df
df2 = df2[
    (df2['lat'] >= LAT_MIN) & (df2['lat'] <= LAT_MAX) &
    (df2['lon'] >= LON_MIN) & (df2['lon'] <= LON_MAX)
]

print(f"Rows after filtering: {len(df2)}")

df2 = df2.sort_values(by='lat', ascending=False)
print(df2.head())

df2.to_csv("vias_trafegaveis_poa_h3_boundaries_pocket.csv", index=False)

df2 = df2.sort_values(by='lat', ascending=True)
print(df2.head())

import shutil
import os
import pandas as pd
import osmium
import h3

# Configuration
DESTINATION_DIR = "/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base"
FILE_FULL = "/content/vias_trafegaveis_poa_h3_boundaries_pocket.csv"
OSM_FILE = "POA.osm.pbf"

# Ensure destination directory exists
os.makedirs(DESTINATION_DIR, exist_ok=True)

# --- 1. Handle vias_trafegaveis_poa_h3.csv (Full Dataset) ---
if not os.path.exists(FILE_FULL):
    print(f"{FILE_FULL} not found. Regenerating from {OSM_FILE}...")

    # Redefine extractor just in case
    class RoadExtractor(osmium.SimpleHandler):
        def __init__(self):
            super().__init__()
            self.rows = []
            self.valid_highways = {
                "motorway", "trunk", "primary", "secondary", "tertiary",
                "unclassified", "residential", "service", "living_street",
                "road", "alley"
            }

        def way(self, w):
            if w.tags.get("highway") not in self.valid_highways:
                return
            for n in w.nodes:
                if n.location.valid():
                    self.rows.append({
                        "way_id": w.id,
                        "node_id": n.ref,
                        "lat": n.location.lat,
                        "lon": n.location.lon,
                        "h3_6": h3.latlng_to_cell(n.location.lat, n.location.lon, 6),
                        "h3_8": h3.latlng_to_cell(n.location.lat, n.location.lon, 8),
                        "h3_10": h3.latlng_to_cell(n.location.lat, n.location.lon, 10),
                        "h3_12": h3.latlng_to_cell(n.location.lat, n.location.lon, 12),
                        "h3_13": h3.latlng_to_cell(n.location.lat, n.location.lon, 13),
                        "h3_15": h3.latlng_to_cell(n.location.lat, n.location.lon, 15),
                    })

    if os.path.exists(OSM_FILE):
        handler = RoadExtractor()
        handler.apply_file(OSM_FILE, locations=True)
        df_full = pd.DataFrame(handler.rows)
        df_full.to_csv(FILE_FULL, index=False)
        print(f"Regenerated {FILE_FULL} with {len(df_full)} rows.")
    else:
        print(f"Error: {OSM_FILE} not found. Cannot regenerate {FILE_FULL}.")

# Move the full file
if os.path.exists(FILE_FULL):
    dest_path = os.path.join(DESTINATION_DIR, FILE_FULL)
    try:
        shutil.move(FILE_FULL, dest_path)
        print(f"Moved: {FILE_FULL} -> {dest_path}")
    except Exception as e:
        print(f"Error moving {FILE_FULL}: {e}")
else:
    print(f"Skipping move for {FILE_FULL} (not found).")

# --- 2. Verification for vias_trafegaveis_poa_h3_boundaries.csv ---
# This file was handled in the previous step, checking existence in Drive
#file_bound = "vias_trafegaveis_poa_h3_boundaries.csv"
file_bound = "/content/vias_trafegaveis_poa_h3_boundaries_pocket.csv"
dest_bound = os.path.join(DESTINATION_DIR, file_bound)

if os.path.exists(dest_bound):
    print(f"Verified: {file_bound} exists in destination.")
else:
    print(f"Warning: {file_bound} is missing from destination.")