# -*- coding: utf-8 -*-
"""pipeline_openmeteo_pythermalcomfort_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hFhSlNIYMJCHcPMz_Zf0P3BdHYEkeTf2

# Pipeline Open‑Meteo + PyThermalComfort — versão aprimorada

Este notebook lê a base climática exportada da **Open‑Meteo Historical Weather API** ou da Forecast API, corrige problemas de tipo de dados, calcula índices de conforto/desconforto térmico com `pythermalcomfort` e gera uma base enriquecida para modelos posteriores.

Ele foi ajustado para a sua base `Weather_regular.xlsx`, que contém variáveis como `temperature_2m`, `relative_humidity_2m`, `dew_point_2m`, `apparent_temperature`, `precipitation`, `rain`, `weather_code`, `pressure_msl`, `cloud_cover`, `wind_speed_10m`, `wind_speed_100m` e temperaturas do solo.

## O que esta versão melhora

1. Reconhece que a estrutura da sua base se aproxima da **Historical Weather API** da Open‑Meteo.
2. Corrige automaticamente decimais que o Excel interpretou como datas, por exemplo `22.9` virando `22/09`.
3. Trata corretamente o fuso horário quando a coluna `time` contém `-03:00`.
4. Converte vento de km/h para m/s apenas quando necessário.
5. Usa `wind_gusts_10m`, caso exista em uma nova exportação, para melhorar a pontuação de vento forte.
6. Gera relatório de qualidade da base antes dos cálculos.
7. Exporta base enriquecida, resumo diário e relatório de qualidade.
"""

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# 1. Instalação das dependências
# ============================================================
# No Google Colab, rode esta célula uma vez.

# %pip -q install "pythermalcomfort>=4.0,<5" openpyxl pyarrow

# ============================================================
# 2. Imports
# ============================================================

from pathlib import Path
from datetime import datetime, date, timedelta
import json
import re
import warnings

import numpy as np
import pandas as pd

from pythermalcomfort import __version__ as pythermalcomfort_version
from pythermalcomfort.models import (
    utci,
    heat_index_rothfusz,
    heat_index_lu,
    humidex,
    at as apparent_temperature_model,
    wind_chill_temperature,
    wci,
    discomfort_index,
)

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings(
    "ignore",
    message=r"datetime\.datetime\.utcnow\(\) is deprecated.*",
    category=DeprecationWarning,
)

pd.set_option("display.max_columns", 160)
pd.set_option("display.width", 180)

print("pythermalcomfort:", pythermalcomfort_version)

# ============================================================
# 3. Configurações gerais
# ============================================================

CONFIG = {
    # Caminho de entrada no Colab.
    # Ajuste se o arquivo estiver no Drive.
    "input_path": "/content/Weather_regular.xlsx",
    "fallback_input_path": "/mnt/data/Weather_regular.xlsx",

    # Saídas.
    "output_csv_path": "weather_pythermalcomfort_enriched.csv",
    "output_parquet_path": "weather_pythermalcomfort_enriched.parquet",
    "output_daily_summary_path": "weather_pythermalcomfort_daily_summary.csv",
    "output_quality_report_path": "weather_openmeteo_quality_report.csv",
    "output_metadata_path": "weather_pythermalcomfort_metadata.json",

    # Fuso horário esperado da pesquisa.
    # A sua base contém horários com -03:00. Esta configuração preserva o horário local.
    "target_timezone": "America/Sao_Paulo",

    # Colunas da Open-Meteo.
    "time_col": "time",
    "location_col": "location_id",
    "temperature_col": "temperature_2m",
    "humidity_col": "relative_humidity_2m",
    "dew_point_col": "dew_point_2m",
    "apparent_temperature_col": "apparent_temperature",
    "precipitation_col": "precipitation",
    "rain_col": "rain",
    "weather_code_col": "weather_code",
    "pressure_col": "pressure_msl",
    "surface_pressure_col": "surface_pressure",
    "cloud_cover_col": "cloud_cover",
    "wind_10m_col": "wind_speed_10m",
    "wind_100m_col": "wind_speed_100m",

    # Colunas opcionais recomendadas para futuras extrações Open-Meteo.
    "wind_gusts_10m_col": "wind_gusts_10m",
    "shortwave_radiation_col": "shortwave_radiation",
    "direct_radiation_col": "direct_radiation",
    "is_day_col": "is_day",
    "sunshine_duration_col": "sunshine_duration",

    # A Open-Meteo usa km/h por padrão para vento quando não se altera wind_speed_unit.
    # Opções aceitas: "kmh" ou "mps".
    "wind_speed_unit": "kmh",
    "use_wind_gusts_if_available": True,

    # Temperatura radiante média para UTCI.
    # Opções:
    # - "air_temperature": tr = tdb. Mais conservador quando não há radiação solar.
    # - "cloud_proxy": aproxima tr por cobertura de nuvens e horário diurno.
    # - "solar_simple": usa shortwave_radiation se existir; é apenas proxy exploratório.
    "mrt_proxy_method": "air_temperature",
    "mrt_daytime_clear_sky_offset_c": 6.0,
    "mrt_solar_offset_per_100w_m2": 1.0,
    "mrt_solar_max_offset_c": 12.0,
    "mrt_fixed_offset_c": 0.0,

    # Período em que a pontuação deve prevalecer.
    "priority_hour_start": 0,
    "priority_hour_end": 24,
    "priority_period_weight": 1.0,
    "off_period_weight": 1.0,

    # Janela para mudança abrupta.
    "abrupt_change_window_hours": 3,

    # Faixa usual do UTCI para vento: 0,5 a 17 m/s.
    "clip_wind_for_utci": True,
    "utci_min_wind_mps": 0.5,
    "utci_max_wind_mps": 17.0,

    # Exportação CSV em padrão brasileiro.
    "csv_sep": ";",
    "csv_decimal": ",",
}

OPEN_METEO_EXPECTED_COLS = [
    CONFIG["time_col"],
    CONFIG["location_col"],
    CONFIG["temperature_col"],
    CONFIG["humidity_col"],
    CONFIG["dew_point_col"],
    CONFIG["apparent_temperature_col"],
    CONFIG["precipitation_col"],
    CONFIG["rain_col"],
    CONFIG["weather_code_col"],
    CONFIG["pressure_col"],
    CONFIG["surface_pressure_col"],
    CONFIG["cloud_cover_col"],
    CONFIG["wind_10m_col"],
    CONFIG["wind_100m_col"],
]

# ============================================================
# 4. Funções de leitura, correção e validação
# ============================================================

EXCEL_EPOCH = datetime(1899, 12, 30)


def resolve_input_path(config: dict) -> Path:
    """Encontra o arquivo de entrada no Colab ou no ambiente local."""
    candidates = [Path(config["input_path"]), Path(config["fallback_input_path"])]
    for path in candidates:
        if path.exists():
            return path
    raise FileNotFoundError(
        "Arquivo não encontrado. Ajuste CONFIG['input_path'] para o caminho correto."
    )


def date_decimal_to_float(dt: datetime | date) -> float:
    """
    Recupera decimal convertido indevidamente em data pelo Excel.

    Exemplos:
    - 22 de setembro -> 22.9
    - 2 de julho -> 2.7
    - 14 de janeiro -> 14.1

    Para meses 10, 11 e 12, usa month/100, pois nesses casos o valor original
    provavelmente tinha duas casas decimais ou ocorreu ambiguidade de localidade.
    """
    day = float(dt.day)
    month = float(dt.month)
    if 1 <= month <= 9:
        return day + month / 10.0
    return day + month / 100.0


def excel_serial_to_datetime(value: float) -> datetime:
    """Converte número serial do Excel em datetime."""
    return EXCEL_EPOCH + timedelta(days=float(value))


def excel_date_decimal_to_float(value):
    """
    Corrige valores meteorológicos convertidos para data pelo Excel.

    A sua planilha contém células formatadas como d.m. Assim, um valor como 22.9
    pode aparecer internamente como uma data, e precisa ser recuperado como float.
    """
    if pd.isna(value):
        return np.nan

    if isinstance(value, pd.Timestamp):
        value = value.to_pydatetime()

    if isinstance(value, datetime) or isinstance(value, date):
        return date_decimal_to_float(value)

    if isinstance(value, str):
        text = value.strip().replace(",", ".")

        # Caso a data tenha vindo como texto dentro de uma coluna numérica.
        if re.match(r"^\d{4}-\d{2}-\d{2}", text):
            parsed = pd.to_datetime(text, errors="coerce")
            if not pd.isna(parsed):
                return excel_date_decimal_to_float(parsed)

        return pd.to_numeric(text, errors="coerce")

    # Caso raro: pandas pode devolver o serial numérico do Excel em vez de Timestamp.
    numeric = pd.to_numeric(value, errors="coerce")
    if pd.isna(numeric):
        return np.nan
    if 35000 <= float(numeric) <= 60000:
        return date_decimal_to_float(excel_serial_to_datetime(float(numeric)))
    return float(numeric)


def clean_numeric_weather_column(series: pd.Series) -> pd.Series:
    """Aplica correção de datas indevidas e converte a coluna para float."""
    return series.map(excel_date_decimal_to_float).astype("float64")


def load_weather_base(config: dict) -> pd.DataFrame:
    """Lê XLSX, CSV ou Parquet e remove colunas de índice criadas em exportações anteriores."""
    input_path = resolve_input_path(config)
    print(f"Lendo arquivo: {input_path}")

    suffix = input_path.suffix.lower()
    if suffix in {".xlsx", ".xls"}:
        df = pd.read_excel(input_path, engine="openpyxl")
    elif suffix == ".csv":
        # Tenta primeiro separador padrão; se vier uma única coluna, tenta separador brasileiro.
        df = pd.read_csv(input_path)
        if df.shape[1] == 1:
            df = pd.read_csv(input_path, sep=";", decimal=",")
    elif suffix == ".parquet":
        df = pd.read_parquet(input_path)
    else:
        raise ValueError(f"Formato não suportado: {suffix}")

    cols_to_drop = [
        col for col in df.columns
        if str(col).startswith("Unnamed") or str(col).lower() in {"none", "nan"}
    ]
    df = df.drop(columns=cols_to_drop, errors="ignore")

    return df


def has_timezone_suffix(series: pd.Series, sample_size: int = 1000) -> bool:
    """Detecta se amostras textuais têm sufixo de fuso, como Z, -03:00 ou +0000."""
    sample = series.dropna().astype(str).head(sample_size)
    if sample.empty:
        return False
    return sample.str.contains(r"(Z|[+-]\d{2}:?\d{2})$", regex=True).any()


def parse_openmeteo_time(series: pd.Series, target_timezone: str) -> pd.Series:
    """
    Padroniza a coluna temporal.

    - Se houver sufixo de fuso, converte para target_timezone e remove tzinfo.
    - Se não houver fuso, assume que a Open-Meteo já retornou hora local.
    """
    if has_timezone_suffix(series):
        parsed_utc = pd.to_datetime(series, errors="coerce", utc=True)
        return parsed_utc.dt.tz_convert(target_timezone).dt.tz_localize(None)
    parsed = pd.to_datetime(series, errors="coerce")
    try:
        return parsed.dt.tz_localize(None)
    except Exception:
        return parsed


def openmeteo_weather_code_label(code):
    """Rótulos simplificados dos códigos WMO usados pela Open-Meteo."""
    if pd.isna(code):
        return "desconhecido"
    code = int(code)
    labels = {
        0: "céu limpo",
        1: "principalmente limpo",
        2: "parcialmente nublado",
        3: "encoberto",
        45: "neblina",
        48: "neblina com geada",
        51: "garoa leve", 53: "garoa moderada", 55: "garoa intensa",
        56: "garoa congelante leve", 57: "garoa congelante intensa",
        61: "chuva leve", 63: "chuva moderada", 65: "chuva forte",
        66: "chuva congelante leve", 67: "chuva congelante forte",
        71: "neve leve", 73: "neve moderada", 75: "neve forte",
        77: "grãos de neve",
        80: "pancadas leves", 81: "pancadas moderadas", 82: "pancadas violentas",
        85: "pancadas de neve leves", 86: "pancadas de neve fortes",
        95: "trovoada",
        96: "trovoada com granizo leve", 99: "trovoada com granizo forte",
    }
    return labels.get(code, f"código WMO {code}")


def validate_openmeteo_schema(df: pd.DataFrame, config: dict) -> pd.DataFrame:
    """Gera relatório compacto de qualidade e coerência das colunas principais."""
    rows = []

    for col in OPEN_METEO_EXPECTED_COLS:
        rows.append({
            "check": "schema_expected_column",
            "column": col,
            "status": "ok" if col in df.columns else "missing",
            "detail": "coluna esperada na base Open-Meteo usada pelo pipeline",
        })

    plausible_ranges = {
        config["temperature_col"]: (-60, 65),
        config["humidity_col"]: (0, 100),
        config["dew_point_col"]: (-80, 40),
        config["apparent_temperature_col"]: (-80, 70),
        config["precipitation_col"]: (0, 300),
        config["rain_col"]: (0, 300),
        config["weather_code_col"]: (0, 99),
        config["pressure_col"]: (850, 1100),
        config["surface_pressure_col"]: (800, 1100),
        config["cloud_cover_col"]: (0, 100),
        config["wind_10m_col"]: (0, 180),
        config["wind_100m_col"]: (0, 220),
    }

    for col, (lo, hi) in plausible_ranges.items():
        if col not in df.columns:
            continue
        s = pd.to_numeric(df[col], errors="coerce")
        rows.append({
            "check": "numeric_quality",
            "column": col,
            "status": "ok" if s.notna().any() else "empty_or_invalid",
            "detail": f"min={s.min()}, max={s.max()}, missing={int(s.isna().sum())}, out_of_range={int(((s < lo) | (s > hi)).sum())}",
        })

    return pd.DataFrame(rows)


def prepare_weather_dataframe(df_raw: pd.DataFrame, config: dict) -> pd.DataFrame:
    """Padroniza tempo, corrige variáveis meteorológicas e cria variáveis auxiliares."""
    df = df_raw.copy()

    time_col = config["time_col"]
    if time_col not in df.columns:
        raise KeyError(f"Coluna temporal '{time_col}' não encontrada na base.")

    df["time_local"] = parse_openmeteo_time(df[time_col], config["target_timezone"])

    numeric_cols = [
        config["temperature_col"],
        config["humidity_col"],
        config["dew_point_col"],
        config["apparent_temperature_col"],
        config["precipitation_col"],
        config["rain_col"],
        config["weather_code_col"],
        config["pressure_col"],
        config["surface_pressure_col"],
        config["cloud_cover_col"],
        config["wind_10m_col"],
        config["wind_100m_col"],
        config["wind_gusts_10m_col"],
        config["shortwave_radiation_col"],
        config["direct_radiation_col"],
        config["is_day_col"],
        config["sunshine_duration_col"],
        "soil_temperature_0_to_7cm",
        "soil_temperature_7_to_28cm",
        "soil_temperature_28_to_100cm",
        "soil_temperature_100_to_255cm",
    ]

    for col in numeric_cols:
        if col in df.columns:
            df[col] = clean_numeric_weather_column(df[col])

    # Limites físicos simples para evitar efeitos de erro de tipo.
    hum = config["humidity_col"]
    cloud = config["cloud_cover_col"]
    wind = config["wind_10m_col"]
    gust = config["wind_gusts_10m_col"]

    if hum in df.columns:
        df[hum] = df[hum].clip(0, 100)
    if cloud in df.columns:
        df[cloud] = df[cloud].clip(0, 100)
    if wind in df.columns:
        df[wind] = df[wind].clip(lower=0)
    if gust in df.columns:
        df[gust] = df[gust].clip(lower=0)

    # Componentes temporais.
    df["date"] = df["time_local"].dt.date
    df["hour"] = df["time_local"].dt.hour
    df["month"] = df["time_local"].dt.month
    df["dayofweek"] = df["time_local"].dt.dayofweek

    # Período prioritário: 06:00 a 20:00.
    start = config["priority_hour_start"]
    end = config["priority_hour_end"]
    df["is_priority_period_06_20"] = df["hour"].between(start, end, inclusive="both")
    df["thermal_time_weight"] = np.where(
        df["is_priority_period_06_20"],
        config["priority_period_weight"],
        config["off_period_weight"],
    )

    # Conversão de vento.
    wind_col = config["wind_10m_col"]
    if wind_col not in df.columns:
        raise KeyError(f"Coluna de vento '{wind_col}' não encontrada.")

    if config["wind_speed_unit"].lower() == "kmh":
        df["wind_speed_10m_kmh"] = df[wind_col]
        df["wind_speed_10m_mps"] = df[wind_col] / 3.6
        if gust in df.columns:
            df["wind_gusts_10m_kmh"] = df[gust]
            df["wind_gusts_10m_mps"] = df[gust] / 3.6
    elif config["wind_speed_unit"].lower() == "mps":
        df["wind_speed_10m_mps"] = df[wind_col]
        df["wind_speed_10m_kmh"] = df[wind_col] * 3.6
        if gust in df.columns:
            df["wind_gusts_10m_mps"] = df[gust]
            df["wind_gusts_10m_kmh"] = df[gust] * 3.6
    else:
        raise ValueError("CONFIG['wind_speed_unit'] deve ser 'kmh' ou 'mps'.")

    if config["use_wind_gusts_if_available"] and "wind_gusts_10m_kmh" in df.columns:
        df["wind_effective_10m_kmh"] = np.maximum(df["wind_speed_10m_kmh"], df["wind_gusts_10m_kmh"])
    else:
        df["wind_effective_10m_kmh"] = df["wind_speed_10m_kmh"]

    # Proxy de temperatura radiante média.
    tdb = config["temperature_col"]
    mrt_method = config["mrt_proxy_method"]
    df["mean_radiant_temperature_proxy"] = df[tdb] + config["mrt_fixed_offset_c"]

    if mrt_method == "cloud_proxy" and config["cloud_cover_col"] in df.columns:
        clear_sky_factor = 1 - (df[config["cloud_cover_col"]] / 100.0)
        daytime_factor = df["is_priority_period_06_20"].astype(float)
        df["mean_radiant_temperature_proxy"] = (
            df[tdb]
            + config["mrt_fixed_offset_c"]
            + daytime_factor * clear_sky_factor * config["mrt_daytime_clear_sky_offset_c"]
        )
    elif mrt_method == "solar_simple" and config["shortwave_radiation_col"] in df.columns:
        solar = df[config["shortwave_radiation_col"]].fillna(0).clip(lower=0)
        solar_offset = (solar / 100.0 * config["mrt_solar_offset_per_100w_m2"]).clip(
            upper=config["mrt_solar_max_offset_c"]
        )
        df["mean_radiant_temperature_proxy"] = df[tdb] + config["mrt_fixed_offset_c"] + solar_offset

    # Rótulo do código meteorológico.
    if config["weather_code_col"] in df.columns:
        df["weather_code_label"] = df[config["weather_code_col"]].map(openmeteo_weather_code_label)

    return df

# ============================================================
# 5. Leitura, correção e diagnóstico inicial
# ============================================================

df_raw = load_weather_base(CONFIG)
print("Dimensão original:", df_raw.shape)
print("Colunas originais:")
print(list(df_raw.columns))
display(df_raw.head())

df = prepare_weather_dataframe(df_raw, CONFIG)
print("Dimensão preparada:", df.shape)
display(df.head())

quality_report = validate_openmeteo_schema(df, CONFIG)
display(quality_report)

print("Período temporal:", df["time_local"].min(), "até", df["time_local"].max())
print("Localidades:", df[CONFIG["location_col"]].nunique() if CONFIG["location_col"] in df.columns else "sem location_id")

essential_cols = [
    CONFIG["time_col"],
    "time_local",
    CONFIG["location_col"],
    CONFIG["temperature_col"],
    CONFIG["humidity_col"],
    CONFIG["wind_10m_col"],
    "wind_speed_10m_mps",
    "wind_effective_10m_kmh",
    "mean_radiant_temperature_proxy",
]
existing_essential_cols = [c for c in essential_cols if c in df.columns]
display(df[existing_essential_cols].describe(include="all"))

# ============================================================
# 6. Funções auxiliares para executar modelos do PyThermalComfort
# ============================================================

def _result_attr(result, attr_name):
    """Extrai atributo de dataclass, dict ou objeto indexável retornado pelo pythermalcomfort."""
    if hasattr(result, attr_name):
        return getattr(result, attr_name)
    if isinstance(result, dict):
        return result.get(attr_name)
    try:
        return result[attr_name]
    except Exception:
        raise AttributeError(f"Não foi possível extrair '{attr_name}' do resultado: {result}")


def _as_1d_array(value, n_expected: int):
    """Converte saída escalar/lista/array em vetor 1D com tamanho esperado."""
    arr = np.asarray(value)
    if arr.shape == ():
        return np.repeat(arr, n_expected)
    return arr.reshape(-1)


def run_pythermal_model(func, attrs, valid_mask, **kwargs):
    """
    Executa um modelo vetorizado do pythermalcomfort somente nas linhas válidas.

    Retorna um dicionário {atributo: array}, preservando NaN nas linhas inválidas.
    """
    n = len(valid_mask)
    idx = np.where(valid_mask)[0]

    output = {attr: np.full(n, np.nan, dtype=object) for attr in attrs}
    if len(idx) == 0:
        return output

    sliced_kwargs = {}
    for key, value in kwargs.items():
        if isinstance(value, (pd.Series, np.ndarray, list, tuple)) and len(value) == n:
            sliced_kwargs[key] = np.asarray(value)[idx]
        else:
            sliced_kwargs[key] = value

    try:
        result = func(**sliced_kwargs)
    except Exception as exc:
        print(f"Falha ao executar {getattr(func, '__name__', str(func))}: {exc}")
        return output

    for attr in attrs:
        values = _as_1d_array(_result_attr(result, attr), len(idx))
        output[attr][idx] = values

    return output

# ============================================================
# 7. Cálculo dos índices térmicos
# ============================================================

# Entradas principais.
tdb = df[CONFIG["temperature_col"]].to_numpy(dtype=float)
rh = df[CONFIG["humidity_col"]].to_numpy(dtype=float)
tr = df["mean_radiant_temperature_proxy"].to_numpy(dtype=float)
wind_mps = df["wind_speed_10m_mps"].to_numpy(dtype=float)
wind_kmh = df["wind_speed_10m_kmh"].to_numpy(dtype=float)

valid_basic = (
    np.isfinite(tdb)
    & np.isfinite(rh)
    & np.isfinite(wind_mps)
    & np.isfinite(tr)
    & (rh >= 0)
    & (rh <= 100)
    & (wind_mps >= 0)
)

# UTCI usa vento a 10 m em m/s.
if CONFIG["clip_wind_for_utci"]:
    wind_mps_utci = np.clip(wind_mps, CONFIG["utci_min_wind_mps"], CONFIG["utci_max_wind_mps"])
else:
    wind_mps_utci = wind_mps

utci_out = run_pythermal_model(
    utci,
    attrs=["utci", "stress_category"],
    valid_mask=valid_basic,
    tdb=tdb,
    tr=tr,
    v=wind_mps_utci,
    rh=rh,
    units="SI",
    limit_inputs=False,
    round_output=False,
)
df["utci_c"] = pd.to_numeric(utci_out["utci"], errors="coerce")
df["utci_stress_category"] = utci_out["stress_category"]

# Temperatura aparente do pythermalcomfort.
at_out = run_pythermal_model(
    apparent_temperature_model,
    attrs=["at"],
    valid_mask=valid_basic,
    tdb=tdb,
    rh=rh,
    v=wind_mps,
    round_output=False,
)
df["pythermal_apparent_temperature_c"] = pd.to_numeric(at_out["at"], errors="coerce")

# Heat Index Rothfusz.
hi_roth_out = run_pythermal_model(
    heat_index_rothfusz,
    attrs=["hi", "stress_category"],
    valid_mask=valid_basic,
    tdb=tdb,
    rh=rh,
    round_output=False,
    limit_inputs=False,
)
df["heat_index_rothfusz_c"] = pd.to_numeric(hi_roth_out["hi"], errors="coerce")
df["heat_index_rothfusz_category"] = hi_roth_out["stress_category"]

# Heat Index Lu/Romps.
hi_lu_out = run_pythermal_model(
    heat_index_lu,
    attrs=["hi"],
    valid_mask=valid_basic,
    tdb=tdb,
    rh=rh,
    round_output=False,
)
df["heat_index_lu_c"] = pd.to_numeric(hi_lu_out["hi"], errors="coerce")

# Humidex.
humidex_out = run_pythermal_model(
    humidex,
    attrs=["humidex", "discomfort"],
    valid_mask=valid_basic,
    tdb=tdb,
    rh=rh,
    model="rana",
    round_output=False,
)
df["humidex_c"] = pd.to_numeric(humidex_out["humidex"], errors="coerce")
df["humidex_discomfort"] = humidex_out["discomfort"]

# Wind Chill Temperature usa vento em km/h.
wct_out = run_pythermal_model(
    wind_chill_temperature,
    attrs=["wct"],
    valid_mask=valid_basic,
    tdb=tdb,
    v=wind_kmh,
    round_output=False,
)
df["wind_chill_temperature_c"] = pd.to_numeric(wct_out["wct"], errors="coerce")

# Wind Chill Index usa vento em m/s e retorna W/m².
wci_out = run_pythermal_model(
    wci,
    attrs=["wci"],
    valid_mask=valid_basic,
    tdb=tdb,
    v=wind_mps,
    round_output=False,
)
df["wind_chill_index_w_m2"] = pd.to_numeric(wci_out["wci"], errors="coerce")

# Discomfort Index: calor/umidade.
di_out = run_pythermal_model(
    discomfort_index,
    attrs=["di", "discomfort_condition"],
    valid_mask=valid_basic,
    tdb=tdb,
    rh=rh,
)
df["discomfort_index_c"] = pd.to_numeric(di_out["di"], errors="coerce")
df["discomfort_index_condition"] = di_out["discomfort_condition"]

display(df[[
    "time_local",
    CONFIG["temperature_col"],
    CONFIG["humidity_col"],
    "wind_speed_10m_kmh",
    "wind_effective_10m_kmh",
    "utci_c",
    "utci_stress_category",
    "heat_index_rothfusz_c",
    "humidex_c",
    "wind_chill_temperature_c",
    "pythermal_apparent_temperature_c",
]].head(10))

# ============================================================
# 8. Mudança abrupta e instabilidade climática
# ============================================================

window = CONFIG["abrupt_change_window_hours"]
loc_col = CONFIG["location_col"]

df = df.sort_values([loc_col, "time_local"]).reset_index(drop=True)

g = df.groupby(loc_col, group_keys=False)
df[f"temperature_delta_{window}h_c"] = g[CONFIG["temperature_col"]].diff(window).abs()
df[f"utci_delta_{window}h_c"] = g["utci_c"].diff(window).abs()
df[f"pressure_delta_{window}h_hpa"] = g[CONFIG["pressure_col"]].diff(window).abs() if CONFIG["pressure_col"] in df.columns else np.nan
df[f"wind_delta_{window}h_kmh"] = g["wind_effective_10m_kmh"].diff(window).abs()


def weather_code_instability_score(code):
    """Transforma código WMO em pontuação de instabilidade climática."""
    if pd.isna(code):
        return 0
    code = int(code)

    if code in {95, 96, 99}:      # trovoadas
        return 90
    if code in {65, 75, 82, 86}:  # precipitação forte
        return 75
    if code in {63, 73, 81, 85}:  # precipitação moderada
        return 55
    if code in {45, 48, 51, 53, 55, 56, 57, 61, 66, 67, 71, 77, 80}:
        return 35
    if code in {3}:               # encoberto
        return 10
    return 0


if CONFIG["weather_code_col"] in df.columns:
    df["weather_code_instability_score"] = df[CONFIG["weather_code_col"]].map(weather_code_instability_score)
else:
    df["weather_code_instability_score"] = 0

# ============================================================
# 9. Pontuação de desconforto térmico configurável
# ============================================================

utci_values = df["utci_c"].to_numpy(dtype=float)

utci_heat_score = np.select(
    [utci_values >= 46, utci_values >= 38, utci_values >= 32, utci_values >= 26],
    [100, 85, 65, 35],
    default=0,
)

utci_cold_score = np.select(
    [utci_values <= -40, utci_values <= -27, utci_values <= -13, utci_values <= 0, utci_values < 9],
    [100, 90, 75, 60, 35],
    default=0,
)

df["score_utci_heat"] = utci_heat_score
df["score_utci_cold"] = utci_cold_score
df["score_utci_thermal"] = np.maximum(utci_heat_score, utci_cold_score)

# Calor + umidade via Heat Index e Humidex.
hi = df["heat_index_rothfusz_c"].to_numpy(dtype=float)
hidx = df["humidex_c"].to_numpy(dtype=float)

df["score_heat_index"] = np.select(
    [hi >= 54, hi >= 41, hi >= 32, hi >= 27],
    [100, 80, 55, 30],
    default=0,
)

df["score_humidex"] = np.select(
    [hidx >= 54, hidx >= 45, hidx >= 40, hidx >= 30],
    [100, 85, 65, 35],
    default=0,
)

# Frio + vento via Wind Chill Temperature.
wct = df["wind_chill_temperature_c"].to_numpy(dtype=float)
tdb_series = df[CONFIG["temperature_col"]].to_numpy(dtype=float)

df["score_wind_chill_cold"] = np.where(
    tdb_series <= 10,
    np.select(
        [wct <= -28, wct <= -10, wct <= 0, wct <= 5],
        [100, 80, 60, 35],
        default=0,
    ),
    0,
)

# Vento forte: usa rajadas se a coluna existir; caso contrário, velocidade média a 10m.
wind_effective = df["wind_effective_10m_kmh"].to_numpy(dtype=float)
df["score_strong_wind"] = np.select(
    [wind_effective >= 70, wind_effective >= 50, wind_effective >= 35, wind_effective >= 25],
    [100, 80, 55, 30],
    default=0,
)

# Mudança abrupta e instabilidade.
temp_delta = df[f"temperature_delta_{window}h_c"].fillna(0).to_numpy(dtype=float)
utci_delta = df[f"utci_delta_{window}h_c"].fillna(0).to_numpy(dtype=float)
pressure_delta = df[f"pressure_delta_{window}h_hpa"].fillna(0).to_numpy(dtype=float)
wind_delta = df[f"wind_delta_{window}h_kmh"].fillna(0).to_numpy(dtype=float)
precip = df[CONFIG["precipitation_col"]].fillna(0).to_numpy(dtype=float) if CONFIG["precipitation_col"] in df.columns else np.zeros(len(df))
cloud = df[CONFIG["cloud_cover_col"]].fillna(0).to_numpy(dtype=float) if CONFIG["cloud_cover_col"] in df.columns else np.zeros(len(df))
weather_instab = df["weather_code_instability_score"].fillna(0).to_numpy(dtype=float)

df["score_abrupt_temperature_change"] = np.clip(np.maximum(temp_delta, utci_delta) / 8.0 * 80, 0, 80)
df["score_pressure_instability"] = np.clip(pressure_delta / 6.0 * 50, 0, 50)
df["score_wind_instability"] = np.clip(wind_delta / 30.0 * 60, 0, 60)
df["score_rain_instability"] = np.select(
    [precip >= 20, precip >= 10, precip >= 3, precip > 0],
    [80, 65, 45, 20],
    default=0,
)
df["score_cloud_instability"] = np.select(
    [cloud >= 95, cloud >= 80],
    [20, 10],
    default=0,
)

df["score_weather_instability"] = np.maximum.reduce([
    df["score_abrupt_temperature_change"].to_numpy(dtype=float),
    df["score_pressure_instability"].to_numpy(dtype=float),
    df["score_wind_instability"].to_numpy(dtype=float),
    df["score_rain_instability"].to_numpy(dtype=float),
    df["score_cloud_instability"].to_numpy(dtype=float),
    weather_instab,
])

# Combinação final.
base_thermal = np.maximum.reduce([
    df["score_utci_thermal"].to_numpy(dtype=float),
    0.90 * df["score_heat_index"].to_numpy(dtype=float),
    0.75 * df["score_humidex"].to_numpy(dtype=float),
    0.85 * df["score_wind_chill_cold"].to_numpy(dtype=float),
])

contextual = (
    0.18 * df["score_weather_instability"].to_numpy(dtype=float)
    + 0.15 * df["score_strong_wind"].to_numpy(dtype=float)
)

raw_score = np.clip(base_thermal + contextual, 0, 100)
df["thermal_discomfort_score_raw"] = raw_score

df["thermal_discomfort_score"] = np.clip(
    df["thermal_discomfort_score_raw"] * df["thermal_time_weight"],
    0,
    100,
).round(2)

df["thermal_discomfort_level"] = pd.cut(
    df["thermal_discomfort_score"],
    bins=[-0.01, 20, 40, 60, 80, 100],
    labels=[
        "baixo ou confortável",
        "desconforto leve",
        "desconforto moderado",
        "desconforto severo",
        "desconforto extremo",
    ],
)

component_cols = [
    "score_utci_heat",
    "score_utci_cold",
    "score_heat_index",
    "score_humidex",
    "score_wind_chill_cold",
    "score_strong_wind",
    "score_weather_instability",
]
component_labels = {
    "score_utci_heat": "calor pelo UTCI",
    "score_utci_cold": "frio pelo UTCI",
    "score_heat_index": "calor e umidade pelo Heat Index",
    "score_humidex": "calor e umidade pelo Humidex",
    "score_wind_chill_cold": "frio com vento",
    "score_strong_wind": "vento forte",
    "score_weather_instability": "tempo instável ou mudança abrupta",
}

max_component = df[component_cols].idxmax(axis=1)
df["thermal_discomfort_main_cause"] = max_component.map(component_labels)
df.loc[df["thermal_discomfort_score"] <= 20, "thermal_discomfort_main_cause"] = "baixo desconforto"

df["thermal_discomfort_flag"] = (df["thermal_discomfort_score"] >= 60).astype(int)

display(df[[
    "time_local",
    CONFIG["location_col"],
    CONFIG["temperature_col"],
    CONFIG["humidity_col"],
    "wind_speed_10m_kmh",
    "wind_effective_10m_kmh",
    "weather_code_label" if "weather_code_label" in df.columns else CONFIG["weather_code_col"],
    "utci_c",
    "utci_stress_category",
    "thermal_discomfort_score",
    "thermal_discomfort_level",
    "thermal_discomfort_main_cause",
    "thermal_discomfort_flag",
]].head(20))

# ============================================================
# 10. Resumos analíticos
# ============================================================

summary_cols = {
    "thermal_discomfort_score": ["mean", "max"],
    "thermal_discomfort_flag": "sum",
    CONFIG["temperature_col"]: ["mean", "min", "max"],
    "utci_c": ["mean", "min", "max"],
    "wind_speed_10m_kmh": ["mean", "max"],
    "wind_effective_10m_kmh": ["mean", "max"],
    CONFIG["precipitation_col"]: ["sum", "max"],
}

summary_cols = {k: v for k, v in summary_cols.items() if k in df.columns}

daily_summary = (
    df.groupby([CONFIG["location_col"], "date"])
      .agg(summary_cols)
)

daily_summary.columns = ["_".join(col).strip("_") for col in daily_summary.columns.to_flat_index()]
daily_summary = daily_summary.reset_index()

daily_summary = daily_summary.rename(columns={
    "thermal_discomfort_score_mean": "daily_discomfort_score_mean",
    "thermal_discomfort_score_max": "daily_discomfort_score_max",
    "thermal_discomfort_flag_sum": "hours_with_severe_or_extreme_discomfort",
})

display(daily_summary.head())

top_events = df.sort_values("thermal_discomfort_score", ascending=False).head(30)
display(top_events[[
    "time_local",
    CONFIG["location_col"],
    CONFIG["temperature_col"],
    CONFIG["humidity_col"],
    "wind_effective_10m_kmh",
    CONFIG["precipitation_col"],
    "weather_code_label" if "weather_code_label" in df.columns else CONFIG["weather_code_col"],
    "utci_c",
    "thermal_discomfort_score",
    "thermal_discomfort_level",
    "thermal_discomfort_main_cause",
]])

# ============================================================
# 11. Visualizações rápidas
# ============================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
df["thermal_discomfort_score"].hist(bins=50)
plt.title("Distribuição da pontuação de desconforto térmico")
plt.xlabel("Score de desconforto térmico")
plt.ylabel("Frequência")
plt.show()

time_series = (
    df.groupby("time_local", as_index=False)["thermal_discomfort_score"]
      .mean()
      .sort_values("time_local")
)

plt.figure(figsize=(14, 5))
plt.plot(time_series["time_local"], time_series["thermal_discomfort_score"])
plt.title("Score médio de desconforto ao longo do tempo")
plt.xlabel("Tempo")
plt.ylabel("Score médio")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

hourly = df.groupby("hour", as_index=False)["thermal_discomfort_score"].mean()
plt.figure(figsize=(10, 5))
plt.bar(hourly["hour"], hourly["thermal_discomfort_score"])
plt.title("Score médio por hora do dia")
plt.xlabel("Hora")
plt.ylabel("Score médio")
plt.xticks(range(0, 24))
plt.show()

# ============================================================
# 12. Exportação da base enriquecida e metadados
# ============================================================

df_export = df.copy()
for col in df_export.select_dtypes(include=["category"]).columns:
    df_export[col] = df_export[col].astype(str)

# CSV em padrão brasileiro.
df_export.to_csv(
    CONFIG["output_csv_path"],
    index=False,
    sep=CONFIG["csv_sep"],
    decimal=CONFIG["csv_decimal"],
    encoding="utf-8-sig",
)

# Parquet para análises maiores.
df_export.to_parquet(CONFIG["output_parquet_path"], index=False)

daily_summary.to_csv(
    CONFIG["output_daily_summary_path"],
    index=False,
    sep=CONFIG["csv_sep"],
    decimal=CONFIG["csv_decimal"],
    encoding="utf-8-sig",
)

quality_report.to_csv(
    CONFIG["output_quality_report_path"],
    index=False,
    sep=CONFIG["csv_sep"],
    decimal=CONFIG["csv_decimal"],
    encoding="utf-8-sig",
)

metadata = {
    "source": "Open-Meteo Historical/Forecast API export",
    "pythermalcomfort_version": pythermalcomfort_version,
    "input_file": str(resolve_input_path(CONFIG)),
    "rows": int(len(df_export)),
    "locations": int(df_export[CONFIG["location_col"]].nunique()) if CONFIG["location_col"] in df_export.columns else None,
    "time_min": str(df_export["time_local"].min()),
    "time_max": str(df_export["time_local"].max()),
    "wind_speed_unit_assumed": CONFIG["wind_speed_unit"],
    "target_timezone": CONFIG["target_timezone"],
    "mrt_proxy_method": CONFIG["mrt_proxy_method"],
    "priority_period": f"{CONFIG['priority_hour_start']:02d}:00-{CONFIG['priority_hour_end']:02d}:00",
    "recommended_future_openmeteo_columns": [
        "wind_gusts_10m",
        "shortwave_radiation",
        "direct_radiation",
        "is_day",
        "sunshine_duration",
    ],
}

with open(CONFIG["output_metadata_path"], "w", encoding="utf-8") as f:
    json.dump(metadata, f, ensure_ascii=False, indent=2)

print("Arquivos gerados:")
print("-", CONFIG["output_csv_path"])
print("-", CONFIG["output_parquet_path"])
print("-", CONFIG["output_daily_summary_path"])
print("-", CONFIG["output_quality_report_path"])
print("-", CONFIG["output_metadata_path"])

"""## Como usar os dados enriquecidos em modelos posteriores

A coluna principal para modelagem é:

- `thermal_discomfort_score`: pontuação contínua de 0 a 100.

Colunas auxiliares importantes:

- `thermal_discomfort_level`: classe interpretável do desconforto.
- `thermal_discomfort_flag`: marcação binária para horas com desconforto severo ou extremo.
- `thermal_discomfort_main_cause`: causa dominante da marcação.
- `utci_c`, `heat_index_rothfusz_c`, `humidex_c`, `wind_chill_temperature_c`, `pythermal_apparent_temperature_c`: índices térmicos derivados do `pythermalcomfort`.
- `weather_code_label`: interpretação textual do código WMO da Open‑Meteo.
- `wind_effective_10m_kmh`: vento usado para pontuar vento forte; usa rajadas se `wind_gusts_10m` existir.

Para ligar isso ao pipeline de corridas por aplicativo, faça `merge` por `location_id` e hora local arredondada, ou por H3/região caso a sua base final use células espaciais.

"""

# ============================================================
# 13. Exemplo de merge com base de corridas
# ============================================================
# Ajuste os nomes de coluna conforme a sua base.

# trips = pd.read_parquet("trips.parquet")
# trips["request_hour"] = pd.to_datetime(trips["request_ts"]).dt.floor("h")
#
# df_weather_merge = df_export[[
#     CONFIG["location_col"],
#     "time_local",
#     "thermal_discomfort_score",
#     "thermal_discomfort_level",
#     "thermal_discomfort_flag",
#     "thermal_discomfort_main_cause",
#     "weather_code_label" if "weather_code_label" in df_export.columns else CONFIG["weather_code_col"],
#     "utci_c",
#     "heat_index_rothfusz_c",
#     "humidex_c",
#     "wind_chill_temperature_c",
# ]].rename(columns={"time_local": "request_hour"})
#
# trips_enriched = trips.merge(
#     df_weather_merge,
#     on=[CONFIG["location_col"], "request_hour"],
#     how="left",
# )
#
# trips_enriched.to_parquet("trips_enriched_with_thermal_discomfort.parquet", index=False)
# display(trips_enriched.head())

from google.colab import drive
drive.mount('/content/drive')

import shutil
from pathlib import Path

destination_folder = Path("/content/drive/MyDrive/DOUTORADO/DATASETS/DATASETS_PRONTOS/V2/")
destination_folder.mkdir(parents=True, exist_ok=True)

current_dir = Path("/content/")

for file_path in current_dir.glob("*.parquet"):
    if file_path.is_file():
        try:
            shutil.move(str(file_path), str(destination_folder / file_path.name))
            print(f"Moved {file_path.name} to {destination_folder}")
        except Exception as e:
            print(f"Error moving {file_path.name}: {e}")