# -*- coding: utf-8 -*-
"""POA_Airport_Arrivals_and_Departures_2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nje9SNhV8xsUDIZmt9_uWlurrEuOdK4x
"""

from google.colab import drive

# Conectar ao Google Drive
drive.mount('/content/drive')

import pandas as pd

csv_urls = [
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/01%20-%20Janeiro/VRA_20251.csv",
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/02%20-%20Fevereiro/VRA_20252.csv",
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/03%20-%20Mar%C3%A7o/VRA_20253.csv",
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/04%20-%20Abril/VRA_20254.csv",
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/05%20-%20Maio/VRA_20255.csv",
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/06%20-%20Junho/VRA_20256.csv",
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/07%20-%20Julho/VRA_20257.csv",
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/08%20-%20Agosto/VRA_20258.csv",
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/09%20-%20Setembro/VRA_20259.csv",
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/10%20-%20Outubro/VRA_202510.csv",
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/11%20-%20Novembro/VRA_202511.csv",
    "https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Voo%20Regular%20Ativo%20%28VRA%29/2025/12%20-%20Dezembro/VRA_202512.csv"
]

all_data = []

for url in csv_urls:
    file_name = url.split('/')[-1]
    print(f"Baixando arquivo: {file_name}...")
    try:
        # Adicionado low_memory=False para evitar DtypeWarning na coluna de códigos
        df_temp = pd.read_csv(url, sep=';', encoding='latin1', skiprows=1, on_bad_lines='skip', low_memory=False)
        all_data.append(df_temp)
        print("  -> Sucesso com latin1")
    except Exception as e:
        print(f"  -> Erro com latin1: {e}. Tentando utf-8...")
        try:
            df_temp = pd.read_csv(url, sep=';', encoding='utf-8', skiprows=1, on_bad_lines='skip', low_memory=False)
            all_data.append(df_temp)
            print("  -> Sucesso com utf-8")
        except Exception as e2:
            print(f"  -> Erro ao baixar ou processar {file_name}: {e2}")

if all_data:
    df_voos = pd.concat(all_data, ignore_index=True)
    print(f"\nExtração concluída! Total de registros consolidados: {len(df_voos)}")
    display(df_voos.head())
    display(df_voos.info())
else:
    print("\nNão foi possível extrair dados de nenhum arquivo CSV.")

import unicodedata
import re

def normalize_columns(name):
    # Tenta corrigir possíveis problemas de codificação (mojibake) vindos do CSV
    try:
        name = name.encode('latin1').decode('utf-8')
    except Exception:
        pass

    # Remove acentuação
    name = unicodedata.normalize('NFKD', name).encode('ASCII', 'ignore').decode('utf-8')

    # Remove caracteres especiais (como parênteses)
    name = re.sub(r'[^\w\s]', '', name)

    # Substitui espaços por subtraço e converte para maiúsculo (ou minúsculo, como preferir)
    name = re.sub(r'\s+', '_', name.strip())

    return name.upper()

# Aplicando a normalização nos cabeçalhos
df_voos.columns = [normalize_columns(col) for col in df_voos.columns]

print("Novos nomes das colunas:")
print(df_voos.columns.tolist())

# Exibir as primeiras linhas para conferência
display(df_voos.head())

# Filtrar somente voos com destino a SBPA
df_voos_sbpa = df_voos[df_voos['ICAO_AERODROMO_DESTINO'] == 'SBPA'].copy()

print(f"Total de voos com destino a SBPA: {len(df_voos_sbpa)}")

# Exibir as primeiras linhas do DataFrame filtrado
display(df_voos_sbpa.head())

"""### Análise de Atrasos dos Voos para SBPA

Nesta etapa, vamos identificar os voos atrasados e o grau de severidade do atraso.

**Metodologia:**
1. **Conversão de Tipos:** Primeiro, garantimos que as colunas `CHEGADA_PREVISTA` e `CHEGADA_REAL` sejam interpretadas como datas e horas (formato *datetime*).
2. **Cálculo do Atraso:** Subtraímos a previsão da chegada real para obter a diferença em minutos.
3. **Definição de Limites (Thresholds):** Na aviação comercial (padrão de agências como a FAA e ANAC), um voo é geralmente considerado "No Prazo" se chegar em até 14 minutos e 59 segundos após o horário estipulado. Com base nisso, classificamos os voos nas seguintes categorias:
   * **No Prazo:** Chegou antes da hora ou com menos de 15 minutos de atraso.
   * **Atraso Leve:** Atraso entre 15 e 59 minutos.
   * **Atraso Moderado:** Atraso entre 1 hora (60 min) e 2 horas (119 min).
   * **Atraso Grave:** Atraso de 2 horas (120 min) ou mais.
   * **Desconhecido / Cancelado:** Voos sem registro de horário de chegada real.
"""

import numpy as np

# 1. Converter as colunas de data/hora para o formato datetime do pandas
# Usamos errors='coerce' para transformar valores inválidos (ou vazios) em NaT (Not a Time)
df_voos_sbpa['CHEGADA_PREVISTA'] = pd.to_datetime(df_voos_sbpa['CHEGADA_PREVISTA'], errors='coerce')
df_voos_sbpa['CHEGADA_REAL'] = pd.to_datetime(df_voos_sbpa['CHEGADA_REAL'], errors='coerce')

# 2. Calcular o tempo de atraso em minutos
# Se o resultado for negativo, significa que o voo chegou adiantado.
df_voos_sbpa['ATRASO_MINUTOS'] = (df_voos_sbpa['CHEGADA_REAL'] - df_voos_sbpa['CHEGADA_PREVISTA']).dt.total_seconds() / 60

# 3. Criar a regra de classificação do grau de atraso usando numpy.select
condicoes = [
    (df_voos_sbpa['ATRASO_MINUTOS'].isna()),                            # Sem horário registrado
    (df_voos_sbpa['ATRASO_MINUTOS'] < 15),                              # Chegou adiantado ou com menos de 15 min de atraso
    (df_voos_sbpa['ATRASO_MINUTOS'] >= 15) & (df_voos_sbpa['ATRASO_MINUTOS'] < 60),  # 15 a 59 min
    (df_voos_sbpa['ATRASO_MINUTOS'] >= 60) & (df_voos_sbpa['ATRASO_MINUTOS'] < 120), # 1 a 2 horas
    (df_voos_sbpa['ATRASO_MINUTOS'] >= 120)                             # 2 horas ou mais
]

# Rótulos para cada condição acima, na mesma ordem
categorias = [
    'Desconhecido / Cancelado',
    'No Prazo (< 15 min)',
    'Atraso Leve (15-59 min)',
    'Atraso Moderado (1-2 h)',
    'Atraso Grave (> 2 h)'
]

# Criar a nova coluna aplicando as condições
df_voos_sbpa['STATUS_ATRASO'] = np.select(condicoes, categorias, default='Outro')

# --- Exibição Explicativa dos Resultados ---

print("='"*20)
print(" RESUMO DOS ATRASOS - DESTINO SBPA")
print("='"*20)

# Contagem de voos por categoria de atraso
resumo_atrasos = df_voos_sbpa['STATUS_ATRASO'].value_counts().reset_index()
resumo_atrasos.columns = ['Status do Voo', 'Quantidade']

# Adicionando percentual para melhor contexto
total_voos = len(df_voos_sbpa)
resumo_atrasos['Percentual (%)'] = (resumo_atrasos['Quantidade'] / total_voos * 100).round(2)

display(resumo_atrasos)

print("\n\nEstatísticas da coluna de minutos de atraso (apenas voos que realmente chegaram):")
display(df_voos_sbpa['ATRASO_MINUTOS'].describe().to_frame().T)

print("\n\nPrimeiras 5 linhas com as novas colunas criadas (foco nas colunas de tempo e status):")
colunas_visualizacao = ['NUMERO_VOO', 'CHEGADA_PREVISTA', 'CHEGADA_REAL', 'ATRASO_MINUTOS', 'STATUS_ATRASO']
display(df_voos_sbpa[colunas_visualizacao].head())

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Extrair apenas a data (sem a hora) da coluna de chegada prevista
df_voos_sbpa['DATA_PREVISTA'] = df_voos_sbpa['CHEGADA_PREVISTA'].dt.date

# 2. Filtrar os dados: remover os voos que estão "No Prazo"
# e descartar registros sem data prevista válida
df_atrasos = df_voos_sbpa[df_voos_sbpa['STATUS_ATRASO'] != 'No Prazo (< 15 min)'].copy()
df_atrasos = df_atrasos.dropna(subset=['DATA_PREVISTA'])

# 3. Agrupar os dados por dia e status de atraso
atrasos_por_dia = df_atrasos.groupby(['DATA_PREVISTA', 'STATUS_ATRASO']).size().reset_index(name='QUANTIDADE')

# 4. Configurar e plotar o gráfico de linhas
plt.figure(figsize=(16, 7))
sns.lineplot(
    data=atrasos_por_dia,
    x='DATA_PREVISTA',
    y='QUANTIDADE',
    hue='STATUS_ATRASO',
    marker='o',
    linewidth=2
)

# Estilização do gráfico
plt.title('Evolução Diária dos Tipos de Atraso em SBPA (Excluindo Voos no Prazo)', fontsize=16)
plt.xlabel('Data Prevista', fontsize=12)
plt.ylabel('Quantidade de Voos Atrasados', fontsize=12)
plt.xticks(rotation=45)
plt.legend(title='Grau de Atraso', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()

# Exibir
plt.show()

# 1. Gráfico de Atrasos por Aeroporto de Origem (Top 10)
plt.figure(figsize=(12, 6))
atrasos_origem = df_atrasos['ICAO_AERODROMO_ORIGEM'].value_counts().head(10).reset_index()
atrasos_origem.columns = ['Origem', 'Quantidade']
sns.barplot(data=atrasos_origem, x='Origem', y='Quantidade', hue='Origem', palette='viridis', legend=False)
plt.title('Top 10 Origens com Mais Voos Atrasados para SBPA', fontsize=14)
plt.xlabel('Aeródromo de Origem (ICAO)', fontsize=12)
plt.ylabel('Quantidade de Voos Atrasados', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 2. Gráfico de Atrasos por Dia da Semana
df_atrasos['DIA_SEMANA'] = df_atrasos['CHEGADA_PREVISTA'].dt.dayofweek
dias_semana_map = {0: 'Segunda', 1: 'Terça', 2: 'Quarta', 3: 'Quinta', 4: 'Sexta', 5: 'Sábado', 6: 'Domingo'}
df_atrasos['NOME_DIA'] = df_atrasos['DIA_SEMANA'].map(dias_semana_map)

plt.figure(figsize=(10, 6))
# Garantir a ordem correta dos dias da semana
atrasos_semana = df_atrasos['NOME_DIA'].value_counts().reindex(dias_semana_map.values()).reset_index()
atrasos_semana.columns = ['Dia da Semana', 'Quantidade']
sns.barplot(data=atrasos_semana, x='Dia da Semana', y='Quantidade', hue='Dia da Semana', palette='magma', legend=False)
plt.title('Quantidade de Voos Atrasados por Dia da Semana', fontsize=14)
plt.xlabel('Dia da Semana', fontsize=12)
plt.ylabel('Quantidade de Voos Atrasados', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 3. Gráfico de Atrasos por Horário (Hora do Dia)
df_atrasos['HORA_PREVISTA'] = df_atrasos['CHEGADA_PREVISTA'].dt.hour
plt.figure(figsize=(12, 6))
atrasos_hora = df_atrasos['HORA_PREVISTA'].value_counts().sort_index().reset_index()
atrasos_hora.columns = ['Hora do Dia', 'Quantidade']
sns.lineplot(data=atrasos_hora, x='Hora do Dia', y='Quantidade', marker='o', color='crimson', linewidth=2)
plt.title('Quantidade de Voos Atrasados por Hora do Dia (Chegada Prevista)', fontsize=14)
plt.xlabel('Hora do Dia (0-23)', fontsize=12)
plt.ylabel('Quantidade de Voos Atrasados', fontsize=12)
plt.xticks(range(0, 24))
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Definir as colunas para a combinação múltipla
colunas_agrupamento = ['ICAO_EMPRESA_AEREA', 'CODIGO_TIPO_LINHA', 'ICAO_AERODROMO_ORIGEM', 'NOME_DIA']

# Agrupar, contar as ocorrências e resetar o índice
combinacoes_recorrentes = df_atrasos.groupby(colunas_agrupamento).size().reset_index(name='QUANTIDADE_ATRASOS')

# Ordenar do maior para o menor (ordem decrescente)
combinacoes_recorrentes = combinacoes_recorrentes.sort_values(by='QUANTIDADE_ATRASOS', ascending=False).reset_index(drop=True)

print("='"*20)
print(" TOP 20 COMBINAÇÕES MAIS RECORRENTES DE ATRASOS")
print("='"*20)
display(combinacoes_recorrentes.head(20))

# --- Visualização do Top 10 ---
top_10_comb = combinacoes_recorrentes.head(10).copy()

# Criar um rótulo único juntando as informações para o gráfico
top_10_comb['ROTULO_COMBINACAO'] = (
    top_10_comb['ICAO_EMPRESA_AEREA'] + " | " +
    top_10_comb['CODIGO_TIPO_LINHA'] + " | " +
    top_10_comb['ICAO_AERODROMO_ORIGEM'] + " | " +
    top_10_comb['NOME_DIA']
)

plt.figure(figsize=(12, 6))
sns.barplot(
    data=top_10_comb,
    y='ROTULO_COMBINACAO',
    x='QUANTIDADE_ATRASOS',
    hue='ROTULO_COMBINACAO',
    palette='Reds_r',
    legend=False
)

plt.title('Top 10 Cenários Mais Frequentes de Atraso em SBPA', fontsize=15)
plt.xlabel('Quantidade de Atrasos', fontsize=12)
plt.ylabel('Cia Aérea | Tipo Linha | Origem | Dia da Semana', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""A análise combinada foi concluída com sucesso!

Olhando para os resultados, podemos ver claramente quais cenários são os maiores responsáveis pelos atrasos em SBPA. O top 3 de combinações mais recorrentes é composto por:

TAM | Linha Nacional (N) | Origem Guarulhos (SBGR) | Sexta-feira: 144 atrasos.
TAM | Linha Nacional (N) | Origem Guarulhos (SBGR) | Quarta-feira: 137 atrasos.
TAM | Linha Nacional (N) | Origem Congonhas (SBSP) | Sexta-feira: 135 atrasos.
Notamos que a companhia TAM operando voos domésticos (N) a partir dos aeroportos de São Paulo (SBGR e SBSP) domina as primeiras posições, especialmente às quartas e sextas-feiras. A AZU (Azul) a partir de Campinas (SBKP) e a GLO (Gol) a partir de Congonhas (SBSP) também aparecem logo em seguida no ranking.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Calcular o total de voos por empresa para SBPA
total_voos_cia = df_voos_sbpa['ICAO_EMPRESA_AEREA'].value_counts().reset_index()
total_voos_cia.columns = ['ICAO_EMPRESA_AEREA', 'TOTAL_VOOS']

# 2. Calcular o total de voos atrasados por empresa (usando df_atrasos)
voos_atrasados_cia = df_atrasos['ICAO_EMPRESA_AEREA'].value_counts().reset_index()
voos_atrasados_cia.columns = ['ICAO_EMPRESA_AEREA', 'VOOS_ATRASADOS']

# 3. Mesclar os DataFrames
analise_cia = pd.merge(total_voos_cia, voos_atrasados_cia, on='ICAO_EMPRESA_AEREA', how='left')

# Preencher com 0 empresas que não tiveram nenhum atraso (se houver)
analise_cia['VOOS_ATRASADOS'] = analise_cia['VOOS_ATRASADOS'].fillna(0)

# 4. Calcular o percentual (Taxa de Atraso)
analise_cia['TAXA_ATRASO_PERCENTUAL'] = (analise_cia['VOOS_ATRASADOS'] / analise_cia['TOTAL_VOOS'] * 100).round(2)

# 5. Filtrar companhias com volume considerável (ex: mínimo de 50 voos) para relevância estatística
analise_cia_filtrada = analise_cia[analise_cia['TOTAL_VOOS'] >= 50].sort_values(by='TAXA_ATRASO_PERCENTUAL', ascending=False)

print("='"*20)
print(" TAXA DE ATRASO POR COMPANHIA AÉREA (Mín. 50 Voos)")
print("='"*20)
display(analise_cia_filtrada)

# --- Visualização ---
plt.figure(figsize=(12, 6))
ax = sns.barplot(
    data=analise_cia_filtrada,
    x='ICAO_EMPRESA_AEREA',
    y='TAXA_ATRASO_PERCENTUAL',
    hue='ICAO_EMPRESA_AEREA',
    palette='Oranges_r',
    legend=False
)

plt.title('Proporção de Voos Atrasados por Cia Aérea em SBPA', fontsize=15)
plt.xlabel('Companhia Aérea (ICAO)', fontsize=12)
plt.ylabel('Taxa de Atraso (%)', fontsize=12)

# Adicionar o valor exato em cima de cada barra
for p in ax.patches:
    ax.annotate(f'{p.get_height():.1f}%',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center',
                xytext=(0, 9),
                textcoords='offset points')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

""" preparei um código que calcula a Taxa de Atraso (%) de cada companhia aérea. Ele pega o total de voos atrasados e divide pelo total de voos operados pela empresa com destino a SBPA. Também adicionei um filtro para considerar apenas companhias com pelo menos 50 voos no período, evitando que uma empresa com 1 voo e 1 atraso apareça com 100% no topo do gráfico.

O código foi executado com sucesso e o gráfico nos revelou um cenário bem interessante em relação à proporção dos atrasos!

Se olharmos apenas para o volume total, companhias como Azul (AZU), TAM e Gol (GLO) têm muitos voos atrasados porque operam muitos voos. Mas quando calculamos a taxa de atraso (percentual), vemos que algumas companhias internacionais lideram o ranking proporcionalmente:

TAP (TAP Portugal): Apresentou uma taxa de atraso altíssima, de 55,46% (66 atrasos em 119 voos).
ARG (Aerolíneas Argentinas): Com uma taxa de 27,98% (47 atrasos em 168 voos).
TAM: Das grandes empresas nacionais, é a que apresenta a maior taxa de atraso, beirando os 19,93%.
A Azul (AZU) e a Gol (GLO), apesar do grande volume, possuem taxas de atraso em torno de 16,31% e 15,25%, respectivamente, mostrando uma operação mais pontual na média do que a TAM.
"""

import os

# Definir o diretório de destino no Google Drive
output_dir = '/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base/DADOS_AEROPORTO'

# Criar o diretório caso ele não exista
os.makedirs(output_dir, exist_ok=True)

print(f"Exportando arquivos para:\n{output_dir}\n...")

# Dicionário com o nome do arquivo e o respectivo DataFrame
datasets_para_exportar = {
    '01_todos_voos_consolidados.csv': df_voos,
    '02_voos_destino_sbpa.csv': df_voos_sbpa,
    '03_voos_atrasados_sbpa.csv': df_atrasos,
    '04_atrasos_por_origem.csv': atrasos_origem,
    '05_atrasos_por_dia_semana.csv': atrasos_semana,
    '06_atrasos_por_hora.csv': atrasos_hora,
    '07_combinacoes_fatores_atraso.csv': combinacoes_recorrentes,
    '08_taxa_atraso_por_companhia.csv': analise_cia_filtrada
}

# Salvar cada DataFrame como CSV
for nome_arquivo, df in datasets_para_exportar.items():
    caminho_completo = os.path.join(output_dir, nome_arquivo)
    try:
        # Usando sep=';' e decimal=',' caso vá abrir no Excel em português,
        # mas mantendo padrão utf-8.
        df.to_csv(caminho_completo, index=False, encoding='utf-8', sep=';')
        print(f" -> Salvo com sucesso: {nome_arquivo}")
    except Exception as e:
        print(f" -> Erro ao salvar {nome_arquivo}: {e}")

print("\nExportação concluída com sucesso!")