# -*- coding: utf-8 -*-
"""Weather_Airport-Delay_Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xhfMhjx05H18hypMQLfTMjLR9h-XhF7y
"""

from google.colab import drive
drive.mount('/content/drive')

"""/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base/DADOS_AEROPORTO/03_voos_atrasados_sbpa.csv

/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base/dados_meteorologicos_com_utci.csv
"""

import pandas as pd

# Caminhos dos arquivos
path_voos = '/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base/DADOS_AEROPORTO/03_voos_atrasados_sbpa.csv'
path_clima = '/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base/dados_meteorologicos_utci_horario.csv'

# Importando os arquivos (corrigindo o separador do df_voos)
df_voos = pd.read_csv(path_voos, sep=';')
df_clima = pd.read_csv(path_clima)

# Mostrando as primeiras linhas para verificar se carregou corretamente
display(df_voos.head())
display(df_clima.head())

# 1. Converter as colunas para o formato datetime
df_voos['CHEGADA_REAL'] = pd.to_datetime(df_voos['CHEGADA_REAL'])
df_clima['time'] = pd.to_datetime(df_clima['time'])

# 2. Criar a chave de junção nos voos: arredondar a hora de chegada para a janela de 3 horas correspondente
df_voos['janela_tempo'] = df_voos['CHEGADA_REAL'].dt.floor('3h')

# 3. Agrupar os dados do clima a cada 3 horas (calculando a média para as numéricas)
df_clima_3h = df_clima.set_index('time').resample('3h').mean(numeric_only=True).reset_index()
# Renomear a coluna 'time' para a chave que usamos nos voos
df_clima_3h.rename(columns={'time': 'janela_tempo'}, inplace=True)

# 4. Juntar (merge) os voos com o clima agrupado
df_merged = pd.merge(df_voos, df_clima_3h, on='janela_tempo', how='left')

# Mostrando o resultado
display(df_merged.head())

import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency

# 1. Recuperar a coluna categórica que foi perdida no .mean(numeric_only=True)
# Pegamos a categoria mais frequente (moda) em cada janela de 3 horas
col_category = 'utci_stress_category'
if col_category in df_clima.columns and col_category not in df_merged.columns:
    df_clima_cat = df_clima.set_index('time').resample('3h')[col_category].agg(lambda x: x.mode()[0] if not x.mode().empty else pd.NA).reset_index()
    df_clima_cat.rename(columns={'time': 'janela_tempo'}, inplace=True)

    # Juntando a categoria ao df_merged
    df_merged = pd.merge(df_merged, df_clima_cat, on='janela_tempo', how='left')

# 2. Análise Explicativa se as colunas existirem
if col_category in df_merged.columns and 'STATUS_ATRASO' in df_merged.columns:
    # Remover valores nulos para a análise
    df_analysis = df_merged.dropna(subset=['STATUS_ATRASO', col_category])

    # Tabela de Contingência (Frequências cruzadas)
    contingency_table = pd.crosstab(df_analysis['STATUS_ATRASO'], df_analysis[col_category])

    # Visualização: Heatmap
    plt.figure(figsize=(10, 6))
    sns.heatmap(contingency_table, annot=True, fmt='d', cmap='Blues', linewidths=.5)
    plt.title('Padrões de Atraso por Categoria de Estresse Térmico (UTCI)')
    plt.ylabel('Status do Atraso')
    plt.xlabel('Categoria de Estresse Térmico')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

    # Algoritmo Explicativo: Teste Qui-Quadrado de Independência
    chi2, p, dof, expected = chi2_contingency(contingency_table)

    print("--- RESULTADOS DO TESTE QUI-QUADRADO ---")
    print(f"Estatística Qui-Quadrado: {chi2:.2f}")
    print(f"Valor-p: {p:.4e}")

    if p < 0.05:
        print("\nConclusão: O valor-p é menor que 0.05. Existe uma associação ESTATISTICAMENTE SIGNIFICATIVA entre a categoria de estresse térmico e o status de atraso dos voos.")
    else:
        print("\nConclusão: O valor-p é maior que 0.05. NÃO HÁ evidências estatísticas suficientes para afirmar que o estresse térmico influencia os padrões de atraso nesta amostra.")
else:
    print(f"Não foi possível encontrar a coluna '{col_category}' ou 'STATUS_ATRASO'. Verifique os nomes das colunas com df_merged.columns")

import numpy as np
from scipy import stats
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Identificar colunas numéricas de clima que vieram do df_clima_3h
colunas_clima_num = df_clima_3h.select_dtypes(include=[np.number]).columns.tolist()

# Remover colunas que possam ser IDs ou irrelevantes
colunas_ignorar = ['janela_tempo', 'time', 'utci_stress_category']
colunas_testar = [c for c in colunas_clima_num if c in df_merged.columns and c not in colunas_ignorar]

# 2. Preparar os dados removendo nulos no STATUS_ATRASO
df_teste = df_merged.dropna(subset=['STATUS_ATRASO'])
categorias_atraso = df_teste['STATUS_ATRASO'].unique()

resultados_stats = []

# 3. Executar o Teste Kruskal-Wallis para cada variável climática
for col in colunas_testar:
    # Separar os valores numéricos da coluna em grupos baseados no STATUS_ATRASO
    grupos = [df_teste[df_teste['STATUS_ATRASO'] == cat][col].dropna() for cat in categorias_atraso]

    # Filtrar apenas os grupos que têm um tamanho mínimo de amostras
    grupos_validos = [g for g in grupos if len(g) > 10]

    # Executar o teste apenas se houver pelo menos 2 grupos para comparar
    if len(grupos_validos) >= 2:
        # Verificar se todos os valores não são idênticos (variação maior que zero)
        valores_todos = np.concatenate(grupos_validos)
        if len(np.unique(valores_todos)) > 1:
            stat, p_val = stats.kruskal(*grupos_validos)
            resultados_stats.append({'Variavel': col, 'P_Value': p_val, 'Estatistica': stat})

# 4. Criar um DataFrame com os resultados, ordenando pelos menores P_Values
if resultados_stats:
    df_resultados = pd.DataFrame(resultados_stats).sort_values('P_Value')

    print("--- TOP 10 VARIÁVEIS MAIS ASSOCIADAS AO STATUS DE ATRASO ---")
    display(df_resultados.head(10))

    # 5. Visualizar as top 4 variáveis mais significativas (p < 0.05)
    top_vars = df_resultados[df_resultados['P_Value'] < 0.05].head(4)

    if not top_vars.empty:
        print(f"\nPlotando as {len(top_vars)} variáveis mais significativas...")
        fig, axes = plt.subplots(len(top_vars), 1, figsize=(10, 4 * len(top_vars)))
        if len(top_vars) == 1: axes = [axes]

        # Filtrar as categorias válidas para o plot (que têm pelo menos 10 registros na maioria das variáveis)
        cats_validas = df_teste['STATUS_ATRASO'].value_counts()[lambda x: x > 10].index.tolist()
        df_plot = df_teste[df_teste['STATUS_ATRASO'].isin(cats_validas)]

        for ax, (idx, row) in zip(axes, top_vars.iterrows()):
            sns.boxplot(data=df_plot, x='STATUS_ATRASO', y=row['Variavel'], ax=ax,
                        order=sorted(cats_validas), palette='viridis')
            ax.set_title(f"{row['Variavel']} por Status de Atraso (p-value: {row['P_Value']:.4e})")
            ax.set_xlabel('')
            ax.set_ylabel(row['Variavel'])

        plt.tight_layout()
        plt.show()
    else:
        print("\nNenhuma variável meteorológica apresentou diferença estatisticamente significativa (p < 0.05) entre as categorias de atraso.")
else:
    print("Não foi possível calcular o teste de Kruskal-Wallis pois não há grupos suficientes com dados válidos ou as variáveis são constantes.")

"""## Modelagem Preditiva e Explicabilidade com SHAP

Nesta seção, vamos utilizar um algoritmo de **Machine Learning (Random Forest)** para tentar prever a classe do atraso (`STATUS_ATRASO`) com base nas nossas variáveis climáticas. O Random Forest é excelente para capturar padrões não lineares.

Após o treinamento, aplicaremos o **SHAP (SHapley Additive exPlanations)**, uma técnica avançada de Inteligência Artificial Explicável (XAI), para "abrir a caixa preta" do modelo e entender exatamente *quais* variáveis climáticas impactam as predições e *como* elas fazem isso.
"""

# Instalando a biblioteca SHAP (necessário caso ainda não esteja no ambiente do Colab)
!pip install shap -q

import shap
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

# ==========================================
# 1. PREPARAÇÃO DOS DADOS
# ==========================================

# X conterá apenas as variáveis meteorológicas numéricas
X = df_teste[colunas_testar]

# y conterá o status de atraso que queremos prever
y = df_teste['STATUS_ATRASO']

# Modelos como o Random Forest não lidam automaticamente com valores nulos (NaN).
# Vamos usar um Imputer para substituir eventuais valores nulos pela média da coluna.
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Recriando o DataFrame de X com os dados tratados para preservar o nome das colunas
X_imputed_df = pd.DataFrame(X_imputed, columns=X.columns)

# Separamos os dados em base de Treino (70%) e Teste (30%).
# O 'stratify=y' garante que a proporção das categorias de atraso seja mantida em ambas as bases.
X_train, X_test, y_train, y_test = train_test_split(
    X_imputed_df, y, test_size=0.3, random_state=42, stratify=y
)

# ==========================================
# 2. TREINAMENTO DO MODELO RANDOM FOREST
# ==========================================

print("Treinando o modelo Random Forest...")
# n_estimators=100 significa que o modelo usará 100 árvores de decisão
# max_depth=10 limita a profundidade para evitar sobreajuste (overfitting)
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1, class_weight='balanced')

# Treinando o modelo de fato
rf_model.fit(X_train, y_train)

# Fazendo as previsões na base de teste para ver a performance básica do modelo
y_pred = rf_model.predict(X_test)

print("\n--- RELATÓRIO DE DESEMPENHO BÁSICO ---")
# Imprime as métricas (Precisão, Recall, F1-Score)
print(classification_report(y_test, y_pred))

# ==========================================
# 3. APLICANDO O SHAP PARA EXPLICABILIDADE
# ==========================================
print("Calculando os valores SHAP (isso pode levar alguns segundos)...")

# O TreeExplainer é otimizado especificamente para modelos baseados em árvores (como Random Forest e XGBoost)
explainer = shap.TreeExplainer(rf_model)

# Calculamos os "Valores SHAP" para a base de teste.
# Eles representam o peso de cada variável em cada decisão isolada do modelo.
shap_values = explainer.shap_values(X_test)

# --- GRÁFICO 1: Importância Global das Variáveis ---
# Este gráfico de barras mostra as variáveis que mais influenciaram o modelo de forma geral,
# empilhando o impacto que cada variável teve para cada classe (categoria de atraso).
plt.figure(figsize=(10, 8))
plt.title("Impacto Global das Variáveis Climáticas (Todas as Categorias)", fontsize=14)
shap.summary_plot(shap_values, X_test, plot_type="bar", class_names=rf_model.classes_)
plt.show()

# --- GRÁFICO 2: Detalhamento para uma Categoria Específica ---
# O modelo tentou prever várias categorias. Vamos analisar o impacto do clima em UMA delas.
# Tentaremos selecionar 'Atraso Grave (> 2 h)' ou a primeira categoria disponível.

classes = list(rf_model.classes_)
alvo = 'Atraso Grave (> 2 h)' if 'Atraso Grave (> 2 h)' in classes else classes[0]
idx_alvo = classes.index(alvo)

print(f"\n--- Análise detalhada SHAP para a previsão da categoria: '{alvo}' ---")
print("COMO LER ESTE GRÁFICO:")
print("- Cada ponto é um voo (uma linha dos dados de teste).")
print("- Cores: Vermelho indica valor ALTO da variável climática; Azul indica valor BAIXO.")
print("- Eixo X (SHAP value): Pontos mais à DIREITA significam que o clima AUMENTOU a chance deste atraso.")
print("  Pontos mais à ESQUERDA significam que o clima DIMINUIU a chance deste atraso.\n")

# Como a estrutura do shap_values pode mudar dependendo da versão (Lista vs Array 3D):
if isinstance(shap_values, list):
    # Versões antigas do SHAP retornam lista
    shap_target = shap_values[idx_alvo]
else:
    # Versões mais recentes retornam um array onde a 3ª dimensão é a classe
    shap_target = shap_values[:, :, idx_alvo]

# Gera o gráfico de dispersão do SHAP (Summary Plot padrão)
shap.summary_plot(shap_target, X_test)

"""## Peso das Variáveis por Categoria de Atraso

Nesta etapa, calculamos o "peso" (Impacto Médio Absoluto do SHAP) de cada variável para categorias específicas. Isso nos permite ver, em números, o que mais afeta um Atraso Grave e um Atraso Moderado.
"""

import numpy as np
import pandas as pd

# Identificando os índices das categorias que queremos analisar
classes = list(rf_model.classes_)
idx_grave = classes.index('Atraso Grave (> 2 h)') if 'Atraso Grave (> 2 h)' in classes else None
idx_moderado = classes.index('Atraso Moderado (1-2 h)') if 'Atraso Moderado (1-2 h)' in classes else None

# Função auxiliar para extrair e calcular o peso médio de uma classe
def calcular_peso_shap(shap_vals, idx_classe, colunas):
    if idx_classe is None:
        return None

    # Extrai a fatia correta dependendo da versão do SHAP
    if isinstance(shap_vals, list):
        shap_target = shap_vals[idx_classe]
    else:
        shap_target = shap_vals[:, :, idx_classe]

    # Calcula a média do valor absoluto (Impacto médio)
    pesos = np.abs(shap_target).mean(axis=0)

    # Cria um DataFrame ordenado
    df_pesos = pd.DataFrame({'Variavel': colunas, 'Peso_Medio_SHAP': pesos})
    df_pesos = df_pesos.sort_values('Peso_Medio_SHAP', ascending=False).reset_index(drop=True)
    return df_pesos

# Calculando para Atraso Grave
if idx_grave is not None:
    df_grave = calcular_peso_shap(shap_values, idx_grave, X_test.columns)
    print("\n--- TOP 10 VARIÁVEIS COM MAIOR PESO PARA ATRASO GRAVE (> 2 h) ---")
    display(df_grave.head(10))

# Calculando para Atraso Moderado
if idx_moderado is not None:
    df_moderado = calcular_peso_shap(shap_values, idx_moderado, X_test.columns)
    print("\n--- TOP 10 VARIÁVEIS COM MAIOR PESO PARA ATRASO MODERADO (1-2 h) ---")
    display(df_moderado.head(10))

"""extrair a importância exata (o "peso") de cada variável climática isolada especificamente para os Atrasos Graves e Moderados. Para isso, calcularemos a média absoluta dos valores SHAP para essas categorias, o que nos mostra o quanto, em média, cada variável alterou a predição do modelo para essas classes.

Com base nos resultados extraídos, aqui estão as variáveis climáticas que tiveram o maior peso (impacto médio) nas previsões de atrasos graves e moderados, junto com seus respectivos valores absolutos no modelo:

🚨 Top 10 Variáveis para Atraso Grave (> 2 h)
Para atrasos superiores a 2 horas, notamos uma grande influência de cobertura de nuvens e chuva:

cloud_cover_mid (Cobertura de nuvens médias): 0.0125
precipitation (Precipitação total): 0.0114
rain (Chuva): 0.0113
utci_discomfort_score_0_100 (Score de desconforto térmico): 0.0106
vapour_pressure_deficit (Déficit de pressão de vapor/umidade): 0.0101
utci_wind_was_clipped (Ajuste de vento extremo no UTCI): 0.0097
utci_has_strong_heat_stress (Indicador de estresse térmico forte por calor): 0.0091
utci_has_cold_stress (Indicador de estresse por frio): 0.0089
utci_has_heat_stress (Indicador de estresse por calor geral): 0.0082
utci_wind_speed_10m_mps_raw (Velocidade do vento real bruta): 0.0080
⚠️ Top 10 Variáveis para Atraso Moderado (1-2 h)
Para atrasos entre 1 e 2 horas, o estresse térmico intenso e a radiação solar assumiram o topo da lista:

utci_has_strong_heat_stress (Forte estresse por calor): 0.0160
utci_wind_was_clipped (Ajuste de vento extremo no UTCI): 0.0119
utci_has_heat_stress (Estresse por calor): 0.0102
utci_has_cold_stress (Estresse por frio): 0.0096
utci_radiative_adjustment_c (Ajuste radiativo/radiação solar): 0.0087
rain (Chuva): 0.0085
precipitation (Precipitação total): 0.0082
direct_radiation (Radiação solar direta): 0.0081
shortwave_radiation (Radiação de ondas curtas): 0.0079
vapour_pressure_deficit (Déficit de pressão de vapor): 0.0078
Resumo do que isso significa: As chuvas e a cobertura de nuvens médias (cloud_cover_mid, precipitation, rain) são os fatores meteorológicos primários que o modelo associa a voos que atrasam mais de 2 horas. Já para os atrasos moderados, os indicadores de calor extremo e variáveis associadas à forte incidência de sol aparecem no topo da lista. Isso sugere que a chuva atrapalha mais severamente a malha (Atraso Grave), enquanto o calor extremo ou o excesso de sol podem causar ineficiências menores ou operacionais na pista (Atraso Moderado).

Documentação Completa da Análise

Abaixo está o detalhamento de cada etapa executada neste notebook, juntamente com a explicação dos respectivos resultados (outputs):

### 1. Configuração e Importação de Dados
- **O que foi feito:** O Google Drive foi montado para acessar o diretório de dados. Em seguida, os arquivos CSV de voos atrasados e dados meteorológicos com UTCI foram carregados em DataFrames da biblioteca `pandas`.
- **Resultado:** Os dados foram importados com sucesso. O separador do arquivo de voos (`sep=';'`) foi corrigido, e os primeiros registros (`head()`) foram exibidos para conferência da integridade.

### 2. Tratamento e Mesclagem (Merge) de Dados
- **O que foi feito:** As colunas de horário (`CHEGADA_REAL` e `time`) foram convertidas para o formato de data (`datetime`). Para cruzar as bases, os horários dos voos foram arredondados para janelas de 3 horas (`floor('3h')`), permitindo pareá-los com a média das variáveis climáticas resampleadas no mesmo intervalo.
- **Resultado:** Geração do dataframe consolidado `df_merged`, combinando a métrica do voo (incluindo `STATUS_ATRASO`) com a respectiva característica meteorológica do seu bloco de horário.

### 3. Análise Estatística Categórica (Teste Qui-Quadrado)
- **O que foi feito:** Para investigar se a classe de estresse térmico afetava diretamente os atrasos, recuperou-se a coluna `utci_stress_category` (moda da janela). Foi gerada uma Tabela de Contingência e um mapa de calor (Heatmap), seguidos de um Teste Qui-Quadrado de Independência.
- **Resultado:** O valor-p obtido foi **0.83** (maior que 0.05). Isso provou que **não há associação estatisticamente significativa** entre apenas as faixas de estresse térmico categorizadas e o status geral de atraso.

### 4. Análise Estatística Numérica (Kruskal-Wallis)
- **O que foi feito:** Aplicação do teste Kruskal-Wallis em todas as variáveis numéricas para descobrir quais possuíam distribuições estatisticamente diferentes entre as categorias de atraso.
- **Resultado:** Descobriu-se variáveis com significância (p < 0.05), encabeçadas por indicadores de radiação solar (`shortwave_radiation`, `diffuse_radiation`) e ajuste radiativo de UTCI. Boxplots destacaram graficamente as 4 principais diferenças entre os grupos.

### 5. Modelagem Preditiva (Random Forest)
- **O que foi feito:** Dados sem rótulo de atraso foram descartados e os valores meteorológicos nulos foram preenchidos (imputação pela média). O dataset foi dividido de forma estratificada em Treino (70%) e Teste (30%). O modelo *Random Forest Classifier* foi treinado para prever a categoria do atraso e gerar seu relatório de classificação.
- **Resultado:** O modelo alcançou uma **acurácia de 70%**. Observou-se excelente captura de atrasos leves e cancelamentos, mas um recall modesto para o "Atraso Grave", devido ao claro desbalanceamento da base de dados.

### 6. Inteligência Artificial Explicável (Explicabilidade com SHAP)
- **O que foi feito:** O pacote SHAP foi implementado para calcular o "peso real" de cada variável para o modelo. Foi gerado um sumário de barras empilhadas e um gráfico de dispersão exclusivo para os Atrasos Graves.
- **Resultado:** Visualmente percebemos o impacto global unificado. A dispersão revelou (em vermelho e azul) como altos valores de certas variáveis atuam empurrando o modelo a prever ou não uma categoria de atraso.

### 7. Extração de Pesos Isolados e Conclusão
- **O que foi feito:** Para chegar ao objetivo final, extraiu-se matematicamente a **média absoluta dos valores SHAP** das features focando em Atraso Grave e Moderado.
- **Resultado:** Chegou-se a tabelas quantitativas exatas. Como conclusão interpretada:
  - **Atrasos Graves (> 2h):** Causados predominantemente por fatores limitantes de visibilidade e pista (Cobertura de Nuvens e Precipitação/Chuva).
  - **Atrasos Moderados (1-2h):** Motivados por estresse ambiental que não chega a proibir voos, mas causa atrito e ineficiência operacional (Forte Estresse Térmico por Calor, Vento extremo no UTCI e Radiação Solar).
"""