# -*- coding: utf-8 -*-
"""01_Tempo_e_Temperatura

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bW_virzZZNYP105nkc4eU4khaS7crGQd
"""

from google.colab import drive
drive.mount('/content/drive')

import shutil
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/Weather_2025_v4-1.csv', 'Weather_2025_v4-1.csv')

import pandas as pd

# Caminho do arquivo
path = "Weather_2025_v4-1.csv"

# Leitura do CSV
df = pd.read_csv(path)

# Visão inicial
df.head()



"""apparent_temperature >= 30°C  → calor desconfortável
apparent_temperature <= 10°C  → frio desconfortável

rain > 0.1 mm
OU
precipitation > 0.1


wind_speed >= 8 m/s


(apparent_temperature - temperature_2m) >= 3°C


Δ apparent_temperature >= 4°C em 3h
OU
Δ cloud_cover >= 30%

"""

import pandas as pd
import numpy as np

df = pd.read_csv("Weather_2025_v4-1.csv")

df["time"] = pd.to_datetime(df["time"], utc=True)
df = df.sort_values(["location_id", "time"])

"""#Aplicando o desconforto térmico

**Frio**

Muito frio: temp ≤ 10

Frio desconfortável:

10 < temp ≤ 15 e umidade ≥ 70



---


**Confortável**

18 ≤ temp ≤ 26

40 ≤ umidade ≤ 70


---



**Calor**

Calor seco:

26 < temp < 30 e umidade < 60

Calor úmido (desconforto forte):

temp ≥ 26 e umidade ≥ 60


---



**Muito calor:**

temp ≥ 32 (independente da umidade)

"""

def thermal_discomfort_level(temp, rh):
    # Frio
    if temp <= 10:
        return 3  # muito frio
    if temp <= 15 and rh >= 70:
        return 2  # frio desconfortável

    # Confortável
    if 18 <= temp <= 26 and 40 <= rh <= 70:
        return 0  # confortável

    # Calor
    if temp >= 32:
        return 3  # muito calor
    if temp >= 26 and rh >= 60:
        return 2  # calor úmido
    if temp >= 26:
        return 1  # calor leve

    return 0

df["thermal_discomfort_level"] = df.apply(
    lambda r: thermal_discomfort_level(
        r["temperature_2m"],
        r["relative_humidity_2m"]
    ),
    axis=1
)

df["thermal_discomfort"] = (
    # Frio extremo
    (df["temperature_2m"] <= 10) |

    # Frio úmido
    ((df["temperature_2m"] > 10) & (df["temperature_2m"] <= 15) & (df["relative_humidity_2m"] >= 70)) |

    # Calor úmido
    ((df["temperature_2m"] >= 26) & (df["relative_humidity_2m"] >= 60)) |

    # Muito calor
    (df["temperature_2m"] >= 32)
).astype(float)

"""df["thermal_discomfort"] = (
    (df["temperature_2m"] >= 28.0) |
    (df["temperature_2m"] <= 15.0)
).astype(float)"""

df["rain_flag"] = (
    (df["rain"] > 0.1) |
    (df["precipitation"] > 0.1)
).astype(int)

df["wind_flag"] = (df["wind_speed_100m"] >= 8).astype(int)

"""#Abafamento
df["mugginess"] = (
    (df["apparent_temperature"] - df["temperature_2m"]) >= 3
).astype(int)"""

#Instabilidade
df["temp_change_3h"] = (
    df.groupby("location_id")["apparent_temperature"]
      .diff(3)
      .abs()
)

df["cloud_change_3h"] = (
    df.groupby("location_id")["cloud_cover"]
      .diff(3)
      .abs()
)

df["instability"] = (
    (df["temp_change_3h"] >= 4) |
    (df["cloud_change_3h"] >= 30)
).astype(int)

#Janela de 3 horas
WINDOW = 3

rolling_cols = [
    "thermal_discomfort",
    "rain_flag",
    "wind_flag",
    "thermal_discomfort_level",
    "instability"
]

for col in rolling_cols:
    df[f"{col}_3h"] = (
        df.groupby("location_id")[col]
          .rolling(WINDOW, min_periods=1)
          .max()
          .reset_index(level=0, drop=True)
    )

#Indice de propensão de chamada
df["ride_hailing_favorable"] = (
    (df["thermal_discomfort_3h"] == 1) |
    (df["rain_flag_3h"] == 1) |
    (df["wind_flag_3h"] == 1) |
    (df["instability_3h"] == 1) |
    (df["thermal_discomfort_level_3h"] != 0)
).astype(int)

df["ride_hailing_score"] = (
    2 * df["rain_flag_3h"] +
    1.5 * df["thermal_discomfort_3h"] +
    1.0 * df["wind_flag_3h"] +
    1.0 * df["instability_3h"] +
    0.5 * df["thermal_discomfort_level_3h"]
)

cols = [
    "time",
    "location_id",
    "ride_hailing_favorable",
    "ride_hailing_score",
    "rain_flag_3h",
    "thermal_discomfort_3h",
    "wind_flag_3h",
    "instability_3h",
    "thermal_discomfort_level",
]

print(df[cols].head(20))

print(
    df[df["ride_hailing_favorable"] == 1]
    [cols]
    .head(50)
)

print(df["ride_hailing_favorable"].value_counts())

df["hour"] = df["time"].dt.hour

print(
    df.groupby("hour")["ride_hailing_score"]
      .mean()
      .round(2)
)

from IPython.display import display

display(df[cols].head(2000))

df["time"] = df["time"].dt.tz_convert('America/Sao_Paulo')
print(df[cols].head(20))

display(df.head(2000))

"""Transformando H3 de RES 6 para H3 de RES 12"""

!pip install h3

import h3
from h3 import LatLngPoly

h3_res5_list = df['location'].unique()


all_res12 = set()

for h in h3_res5_list:
    boundary = h3.cell_to_boundary(h)
    poly = LatLngPoly(boundary)
    all_res12.update(h3.polygon_to_cells(poly, 12))

len(all_res12)
print(all_res12)

df.to_csv("Weather_enhanced.csv")
import shutil
shutil.copy('Weather_enhanced.csv','/content/drive/MyDrive/DOUTORADO/DATASETS/DATASETS_PRONTOS/Weather_enhanced.csv')