# -*- coding: utf-8 -*-
"""02_Chegadas_e_Partidas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EaymfmgVRWIV4Mvqbt8gKg0Kcp-7d4_u
"""

from google.colab import drive
drive.mount('/content/drive')

import shutil
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/VOOS_2025/VRA_20251.csv', 'VRA_20251.csv')
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/VOOS_2025/VRA_20252.csv', 'VRA_20252.csv')
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/VOOS_2025/VRA_20253.csv', 'VRA_20253.csv')
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/VOOS_2025/VRA_20254.csv', 'VRA_20254.csv')
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/VOOS_2025/VRA_20255.csv', 'VRA_20255.csv')
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/VOOS_2025/VRA_20256.csv', 'VRA_20256.csv')
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/VOOS_2025/VRA_20257.csv', 'VRA_20257.csv')
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/VOOS_2025/VRA_20258.csv', 'VRA_20258.csv')
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/VOOS_2025/VRA_20259.csv', 'VRA_20259.csv')
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/VOOS_2025/VRA_202510.csv', 'VRA_202510.csv')
shutil.copy('/content/drive/MyDrive/DOUTORADO/DATASETS/VOOS_2025/VRA_202511.csv', 'VRA_202511.csv')

import pandas as pd
import glob

paths = glob.glob('/content/VRA_2025*.csv')

df = pd.concat(
    (pd.read_csv(p, sep=';', low_memory=False) for p in paths),
    ignore_index=True
)

df.info()
df.head()

#Origem ou destino = SBPA (Aeroporto de POA)
df_sbpa = df[
    (df["ICAO Aeródromo Origem"] == "SBPA") |
    (df["ICAO Aeródromo Destino"] == "SBPA")
]

partidas_sbpa = df[df["ICAO Aeródromo Origem"] == "SBPA"]

destino_sbpa = df[df["ICAO Aeródromo Destino"] == "SBPA"]

destino_sbpa[["ICAO Aeródromo Origem", "ICAO Aeródromo Destino"]].value_counts().head()

df_sbpa = df[
    (df["ICAO Aeródromo Origem"] == "SBPA") |
    (df["ICAO Aeródromo Destino"] == "SBPA")
].copy()

import numpy as np

df_sbpa["movimento"] = np.select(
    [
        df_sbpa["ICAO Aeródromo Origem"] == "SBPA",
        df_sbpa["ICAO Aeródromo Destino"] == "SBPA"
    ],
    [
        "partida",
        "chegada"
    ],
    default="outro"
)

#Convertendo datas para datetime
time_cols = [
    "Partida Prevista",
    "Partida Real",
    "Chegada Prevista",
    "Chegada Real"
]

for c in time_cols:
    df_sbpa[c] = pd.to_datetime(df_sbpa[c], errors="coerce", utc=True)

df_sbpa["timestamp"] = np.where(
    df_sbpa["movimento"] == "partida",
    df_sbpa["Partida Real"].fillna(df_sbpa["Partida Prevista"]),
    df_sbpa["Chegada Real"].fillna(df_sbpa["Chegada Prevista"])
)

df_sbpa["timestamp"] = pd.to_datetime(df_sbpa["timestamp"], utc=True)

voos_por_hora = (
    df_sbpa
    .set_index("timestamp")
    .groupby("movimento")
    .resample("3h")   # <- aqui
    .size()
    .rename("n_voos")
    .reset_index()
)

print(voos_por_hora)

df_sbpa.to_csv("df_sbpa.csv")

"""#Criação de OO para os voos


| Coluna CSV              | Objeto    | Campo                |
| ----------------------- | --------- | -------------------- |
| ICAO Empresa Aérea      | Voo       | empresa_icao         |
| Número Voo              | Voo       | numero_voo           |
| Código Autorização (DI) | Voo       | codigo_autorizacao   |
| Código Tipo Linha       | Voo       | tipo_linha           |
| ICAO Aeródromo Origem   | Voo       | origem               |
| ICAO Aeródromo Destino  | Voo       | destino              |
| movimento               | EventoVoo | movimento            |
| Partida Prevista        | EventoVoo | partida_prevista     |
| Partida Real            | EventoVoo | partida_real         |
| Chegada Prevista        | EventoVoo | chegada_prevista     |
| Chegada Real            | EventoVoo | chegada_real         |
| Situação Voo            | EventoVoo | situacao             |
| Código Justificativa    | EventoVoo | codigo_justificativa |
| timestamp               | EventoVoo | timestamp            |

"""

from dataclasses import dataclass

@dataclass(frozen=True)
class Aeroporto:
    icao: str               # "SBPA"

from dataclasses import dataclass

@dataclass(frozen=True)
class Voo:
    numero_voo: str                 # "GLO1234"
    empresa_icao: str               # "GLO"
    codigo_autorizacao: str         # DI
    tipo_linha: str                 # REG, NÃO REG, CARGA...
    origem: Aeroporto
    destino: Aeroporto

from enum import Enum

class MovimentoVoo(Enum):
    CHEGADA = "chegada"
    PARTIDA = "partida"


class SituacaoVoo(Enum):
    REALIZADO = "REALIZADO"
    CANCELADO = "CANCELADO"
    ALTERNADO = "ALTERNADO"
    DESCONHECIDO = "DESCONHECIDO"

from dataclasses import dataclass
from datetime import datetime
from typing import Optional

@dataclass
class EventoVoo:
    voo: Voo

    movimento: MovimentoVoo

    partida_prevista: Optional[datetime]
    partida_real: Optional[datetime]

    chegada_prevista: Optional[datetime]
    chegada_real: Optional[datetime]

    situacao: SituacaoVoo
    codigo_justificativa: Optional[str]

    aeroporto_referencia: Aeroporto   # SBPA
    timestamp: datetime                # timestamp analítico principal

from datetime import timedelta

@dataclass
class EventoVoo:
    ...
    def atraso_partida(self) -> Optional[timedelta]:
        if self.partida_prevista and self.partida_real:
            return self.partida_real - self.partida_prevista
        return None

    def atraso_chegada(self) -> Optional[timedelta]:
        if self.chegada_prevista and self.chegada_real:
            return self.chegada_real - self.chegada_prevista
        return None

    def houve_atraso(self, limite_minutos: int = 15) -> bool:
        atraso = self.atraso_chegada() or self.atraso_partida()
        return atraso is not None and atraso.total_seconds() > limite_minutos * 60

"""Entendendo os voos (se eles destoaram muito da média de tempo de deslocamento e do tempo previsto para o tempo efetivo (chegada e/ou partida))"""

import pandas as pd
import numpy as np

def diff_minutos(real: pd.Series, previsto: pd.Series) -> pd.Series:
    """
    Retorna diferença em minutos (real - previsto)
    """
    return (real - previsto).dt.total_seconds() / 60

def tempo_voo_minutos(df: pd.DataFrame, real=True) -> pd.Series:
    """
    Calcula duração do voo em minutos
    """
    if real:
        return (df["Chegada Real"] - df["Partida Real"]).dt.total_seconds() / 60
    else:
        return (df["Chegada Prevista"] - df["Partida Prevista"]).dt.total_seconds() / 60

def enrich_diffs(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    df["diff_partida_min"] = diff_minutos(
        df["Partida Real"], df["Partida Prevista"]
    )

    df["diff_chegada_min"] = diff_minutos(
        df["Chegada Real"], df["Chegada Prevista"]
    )

    df["tempo_voo_previsto_min"] = tempo_voo_minutos(df, real=False)
    df["tempo_voo_real_min"] = tempo_voo_minutos(df, real=True)

    df["delta_tempo_voo_min"] = (
        df["tempo_voo_real_min"] - df["tempo_voo_previsto_min"]
    )

    return df

"""#Média histórica por combinação origem–destino"""

def baseline_por_rota(df: pd.DataFrame) -> pd.DataFrame:
    """
    Calcula estatísticas por (origem, destino)
    """
    group_cols = ["ICAO Aeródromo Origem", "ICAO Aeródromo Destino"]

    baseline = (
        df.groupby(group_cols)
        .agg(
            media_tempo_voo=("tempo_voo_real_min", "mean"),
            std_tempo_voo=("tempo_voo_real_min", "std"),
            media_diff_partida=("diff_partida_min", "mean"),
            std_diff_partida=("diff_partida_min", "std"),
            media_diff_chegada=("diff_chegada_min", "mean"),
            std_diff_chegada=("diff_chegada_min", "std"),
            n_voos=("Número Voo", "count"),
        )
        .reset_index()
    )

    return baseline

"""#Estimando thresholds automaticamente"""

def add_thresholds(baseline: pd.DataFrame, k: float = 2.0) -> pd.DataFrame:
    baseline = baseline.copy()

    baseline["thr_partida_min"] = (
        baseline["media_diff_partida"] + k * baseline["std_diff_partida"]
    )

    baseline["thr_chegada_min"] = (
        baseline["media_diff_chegada"] + k * baseline["std_diff_chegada"]
    )

    return baseline

"""Enriquecendo o dataset final com flags"""

def flag_outliers(df: pd.DataFrame, baseline: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    df = df.merge(
        baseline[
            [
                "ICAO Aeródromo Origem",
                "ICAO Aeródromo Destino",
                "thr_partida_min",
                "thr_chegada_min",
            ]
        ],
        on=["ICAO Aeródromo Origem", "ICAO Aeródromo Destino"],
        how="left",
    )

    df["outlier_partida"] = (
        df["diff_partida_min"].abs() > df["thr_partida_min"]
    )

    df["outlier_chegada"] = (
        df["diff_chegada_min"].abs() > df["thr_chegada_min"]
    )

    df["outlier_evento"] = df["outlier_partida"] | df["outlier_chegada"]

    return df

"""#Pipeline de leitura e enriquecimento"""

df_enriched = enrich_diffs(df_sbpa)

baseline = baseline_por_rota(df_enriched)
baseline = add_thresholds(baseline, k=2.0)

df_final = flag_outliers(df_enriched, baseline)

print(df_final)

df_final.to_csv('df_sbpa_enriched.csv')
shutil.copy('df_sbpa_enriched.csv','/content/drive/MyDrive/DOUTORADO/DATASETS/DATASETS_PRONTOS/MOVIMENTACAO_AEROPORTO_SBPA_2025.csv')