# -*- coding: utf-8 -*-
"""DISTRIBUICAO_NAO_SIMULADA_V6_FINAL_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKUz85IQLmvulfjj38T-8XdQXN6ViH-7

# Distribuição Não Simulada V6 (fixed ~30 corridas/dia)

Notebook completo reescrito e calibrado para ~30 corridas/dia por motorista (ajustável no topo).
"""

import shutil
import os

folder_to_clear = '/content/generated_data'

if os.path.exists(folder_to_clear):
    shutil.rmtree(folder_to_clear)
    print(f'Folder "{folder_to_clear}" and its contents removed.')

os.makedirs(folder_to_clear, exist_ok=True)
print(f'Folder "{folder_to_clear}" recreated as empty.')

import os
import time
from datetime import datetime

def log_worker(msg):
    pid = os.getpid()
    now = datetime.now().strftime("%H:%M:%S")
    print(f"[{now}] [PID {pid}] {msg}", flush=True)

import gc, psutil, os, tracemalloc

def rss_gb():
    return psutil.Process(os.getpid()).memory_info().rss / 1024**3

def mem(tag):
    gc.collect()
    print(f"{tag:>24} | RSS={rss_gb():.2f} GB")

tracemalloc.start()
mem("start")

# -*- coding: utf-8 -*-
"""DISTRIBUICAO_NAO_SIMULADA_v5_optimized_fixed_30trips

Versão reescrita/calibrada para ~30 corridas/dia por motorista (ordem de grandeza),
mantendo o pipeline e os outputs em Parquet.

Mudanças (além do fix anterior):
- IDLE mais curto (média menor + truncagem da cauda).
- Mais tentativas por minuto durante IDLE.
- call_probability com probabilidade base alta + piso (nunca fica quase zero dentro do raio).
- DESTINATION também local (raio maior) para manter tempos de viagem urbanos e permitir mais corridas/dia.

⚙️ Ajuste fino (topo do arquivo):
- IDLE_MEAN_MINUTES, CALL_BASE_P, CALL_FLOOR_P, CALLS_PER_IDLE_STEP
- CALL_MAX_DIST (origin local) e DEST_MAX_DIST (destination local)
- AVG_SPEED_KMH e KM_PER_H3_CELL
"""

# ============================================================
# 0) Instalação (Colab)
# ============================================================
!pip -q install h3 pandas tqdm pyarrow lxml

# ============================================================
# 1) Imports + Drive + Config
# ============================================================
import os, shutil, random, logging, math
from datetime import datetime, timedelta
from collections import defaultdict
from multiprocessing import Pool

import numpy as np
import pandas as pd
import h3
import pyarrow as pa
import pyarrow.parquet as pq
from google.colab import drive

drive.mount("/content/drive")

TIMEZONE = "UTC"
START_DATE = datetime(2025, 10, 1)
END_DATE   = datetime(2026, 1, 1)  # exclusive (covers full 2025)

TOTAL_DRIVERS = 30_000


WORK_PROBABILITY = {0: 0.8, 1: 0.7, 2: 0.6, 3: 0.7, 4: 1.0, 5: 1.0, 6: 0.9}

# ---------------------------
# CALIBRAÇÃO PARA ~30/dia
# ---------------------------
AVG_SPEED_KMH = 90                 # urbano
KM_PER_H3_CELL = 0.035              # ajuste aproximado (res12); menor => tempos menores
IDLE_MEAN_MINUTES = 2.0            # chave para aumentar corridas/dia
IDLE_MAX_MINUTES = 5.0             # corta cauda longa do exponencial

CALL_MAX_DIST = 120                 # origin local (<=100)
DEST_MAX_DIST = 600                # destination local (<=250)

IDLE_STEP_MINUTES = 1.0            # passo quando não atribui
CALLS_PER_IDLE_STEP = 50           # MAIS tentativas por step (aumenta taxa de match)

CALL_BASE_P  = 0.85                 # probabilidade base alta
CALL_FLOOR_P = 0.70                # piso (não deixa ficar muito baixo dentro do raio)

SHIFT_START_HOUR_MIN = 4.0
SHIFT_START_HOUR_MAX = 10.0

OUTPUT_DIR = "/content/generated_data/outputs_simulation_v6_FINAL"
AGG_DIR  = f"{OUTPUT_DIR}/aggregates"
TRIPS_DIR= f"{OUTPUT_DIR}/trips_log"
LOG_DIR  = f"{OUTPUT_DIR}/logs"
META_DIR = f"{OUTPUT_DIR}/metadata"
for d in [OUTPUT_DIR, AGG_DIR, TRIPS_DIR, LOG_DIR, META_DIR]:
    os.makedirs(d, exist_ok=True)

logging.basicConfig(
    filename=f"{LOG_DIR}/simulation.log",
    level=logging.INFO,
    format="%(asctime)s [%(processName)s] %(message)s"
)

# ============================================================
# 2) Copiar arquivos base (ajuste paths conforme seu Drive)
# ============================================================
base_dir = "/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base"
shutil.copy(f"{base_dir}/vias_trafegaveis_poa_h3_boundaries.csv", "./")
#/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base/DADOS_AEROPORTO/03_voos_atrasados_sbpa.csv
datasets_dir = "/content/drive/MyDrive/DOUTORADO/DATASETS/DATASETS_PRONTOS"
shutil.copy("/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base/dados_meteorologicos_utci_horario.csv", "./")
shutil.copy("/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/arquivos_base/DADOS_AEROPORTO/03_voos_atrasados_sbpa.csv", "./")
shutil.copy(f"{datasets_dir}/Aeroporto_Salgado_Filho_h3_res12.csv", "./")

# ============================================================
# 3) Carregar H3 válidos
# ============================================================
df_h3 = pd.read_csv("/content/vias_trafegaveis_poa_h3_boundaries.csv")
valid_h3s = df_h3["h3_12"].dropna().unique().tolist()
valid_h3s = list(dict.fromkeys(valid_h3s))
valid_set = set(valid_h3s)
M_VALID = len(valid_h3s)
print("valid_h3s:", M_VALID)

# ============================================================
# 4) Modelos rápidos
# ============================================================
#def _floor_to_hour(dt: datetime) -> datetime:
#    return dt.replace(minute=0, second=0, microsecond=0)
HOUR_MS = 3600 * 1000

def _floor_to_hour(dt_or_ms):
    if isinstance(dt_or_ms, (int, float)):
        return (int(dt_or_ms) // HOUR_MS) * HOUR_MS
    return int(dt_or_ms.replace(minute=0, second=0, microsecond=0).timestamp() * 1000)

class TimeModel:
    @staticmethod
    def travel_time_minutes(h3_dist: int) -> float:
        distance_km = max(0.0, float(h3_dist)) * float(KM_PER_H3_CELL)
        speed = max(10.0, random.normalvariate(AVG_SPEED_KMH, 4))
        return (distance_km / speed) * 60.0

    @staticmethod
    def idle_time_minutes(weekday: int) -> float:
        base = float(np.random.exponential(IDLE_MEAN_MINUTES))
        base = min(base, float(IDLE_MAX_MINUTES))  # truncagem: evita idles gigantes
        factor = WORK_PROBABILITY[weekday]
        # dias de mais demanda => menos idle
        return max(1.0, base * (1.05 - 0.55 * factor))

def call_probability(h3_distance: int) -> float:
    if h3_distance <= 0:
        return 1.0
    x = h3_distance / float(CALL_MAX_DIST)
    if x <= 1.0:
        p = float(CALL_BASE_P) * (1.0 - x * x)
        return max(float(CALL_FLOOR_P), p)
    # fora do raio: cai, mas não zera
    return max(0.02, float(CALL_FLOOR_P) / (1.0 + (x - 1.0) * 2.5))

class Event:
    __slots__ = ("name","start","end","affected_h3s","apply_to","weight")
    def __init__(self, name, start, end, affected_h3s, apply_to, weight=1.0):
        self.name = name
        self.start = start.to_pydatetime() if isinstance(start, pd.Timestamp) else start
        self.end   = end.to_pydatetime()   if isinstance(end, pd.Timestamp)   else end
        self.affected_h3s = affected_h3s
        self.apply_to = apply_to
        self.weight = float(weight)

# ============================================================
# 5) DemandModel (alias sampling) + cache por hora
# ============================================================
class _AliasSampler:
    __slots__ = ("items","prob","alias","n")
    def __init__(self, items, weights):
        self.items = items
        n = len(items)
        self.n = n
        if n == 0:
            self.prob, self.alias = [], []
            return
        w = np.array(weights, dtype=np.float64)
        s = w.sum()
        if s <= 0:
            self.prob = [1.0]*n
            self.alias= list(range(n))
            return
        w = w * n / s
        small, large = [], []
        prob = np.zeros(n, dtype=np.float64)
        alias = np.zeros(n, dtype=np.int32)
        for i, wi in enumerate(w):
            if wi < 1.0: small.append(i)
            else: large.append(i)
        while small and large:
            s_i = small.pop()
            l_i = large.pop()
            prob[s_i] = w[s_i]
            alias[s_i] = l_i
            w[l_i] = (w[l_i] + w[s_i]) - 1.0
            if w[l_i] < 1.0: small.append(l_i)
            else: large.append(l_i)
        for i in large + small:
            prob[i] = 1.0
            alias[i] = i
        self.prob = prob.tolist()
        self.alias = alias.tolist()

    def sample(self):
        if self.n == 0:
            return None
        i = random.randrange(self.n)
        if random.random() < self.prob[i]:
            return self.items[i]
        return self.items[self.alias[i]]

class DemandModel:
    def __init__(self, valid_h3s, events):
        self.valid_h3s = valid_h3s
        self.M = len(valid_h3s)
        self.events_by_hour = defaultdict(list)
        for ev in events:
            t = _floor_to_hour(ev.start)
            end_h = _floor_to_hour(ev.end)
            while t <= end_h:
                self.events_by_hour[(ev.apply_to, t)].append(ev)
                #t += timedelta(hours=1)
                t += 3600 * 1000
        self.cache = {}

    def _build_bucket(self, apply_to: str, bucket: datetime):
        active = self.events_by_hour.get((apply_to, bucket), [])
        if not active:
            self.cache[(apply_to, bucket)] = (0.0, None, None, None)
            return
        extra = defaultdict(float)
        best  = {}
        for ev in active:
            w = ev.weight
            for cell in ev.affected_h3s:
                extra[cell] += w
                prev = best.get(cell)
                if prev is None or w > prev[1]:
                    best[cell] = (ev.name, w)
        affected_cells = list(extra.keys())
        affected_weights = [extra[c] for c in affected_cells]
        S = float(sum(affected_weights))
        sampler = _AliasSampler(affected_cells, affected_weights) if S > 0 else None
        self.cache[(apply_to, bucket)] = (S, sampler, best, dict(extra))

    def choose_h3(self, t: datetime, apply_to: str):
        bucket = _floor_to_hour(t)
        key = (apply_to, bucket)
        if key not in self.cache:
            self._build_bucket(apply_to, bucket)
        S, sampler, best, _extra = self.cache[key]
        if S <= 0 or sampler is None:
            cell = random.choice(self.valid_h3s)
            return cell, None
        if random.random() < (self.M / (self.M + S)):
            cell = random.choice(self.valid_h3s)
            return cell, None
        else:
            cell = sampler.sample()
            ev_name = best.get(cell, (None, 0.0))[0]
            return cell, ev_name

    def local_weights(self, t: datetime, apply_to: str):
        bucket = _floor_to_hour(t)
        key = (apply_to, bucket)
        if key not in self.cache:
            self._build_bucket(apply_to, bucket)
        _S, _sampler, best, extra = self.cache[key]
        return (best or {}), (extra or {})

def cache_info(cache, name="cache"):
    # tenta descobrir tamanho/estatísticas sem assumir API
    attrs = ["size", "count", "n", "n_items", "items", "hits", "misses", "stats", "info"]
    out = {"type": type(cache).__name__}
    for a in attrs:
        if hasattr(cache, a):
            try:
                v = getattr(cache, a)
                out[a] = v() if callable(v) else v
            except Exception:
                pass
    print(name, out)

# ============================================================
# 6) Cache de vizinhança H3 (grid_disk) + origin/destination local
# ============================================================
class H3DiskCache:
    def __init__(self, k: int):
        self.k = int(k)
        self._cache = {}
    def disk(self, h3_cell: str):
        d = self._cache.get(h3_cell)
        if d is None:
            d = list(h3.grid_disk(h3_cell, self.k))
            self._cache[h3_cell] = d
        return d

"""def choose_origin_local(current_h3: str,
                       current_time: datetime,
                       demand: DemandModel,
                       disk_cache: H3DiskCache,
                       valid_set: set[str]) -> tuple[str, str|None, int]:
    disk = disk_cache.disk(current_h3)
    local = [c for c in disk if c in valid_set]
    if not local:
        origin, ev_name = demand.choose_h3(current_time, "origin")
        dist = h3.grid_distance(current_h3, origin)
        return origin, ev_name, dist
    best, extra = demand.local_weights(current_time, "origin")
    weights = [1.0 + float(extra.get(c, 0.0)) for c in local]
    origin = random.choices(local, weights=weights, k=1)[0]
    ev_name = best.get(origin, (None, 0.0))[0]
    dist = h3.grid_distance(current_h3, origin)
    return origin, ev_name, dist"""

def choose_origin_local(
        current_h3: str,
        current_time: datetime,
        demand: DemandModel,
        disk_cache: H3DiskCache | None,          # <- permite None
        valid_set: set[str],
    ) -> tuple[str, str | None, int]:
    # --- melhoria cirúrgica: só usa cache se existir ---
    if disk_cache is not None:
        disk = disk_cache.disk(current_h3)
        local = [c for c in disk if c in valid_set]
    else:
        local = []

    # fallback local sem cache (evita origem global)
    if len(local) < 50:
        # anel de vizinhança simples
        for k in (5, 10, 20):
            ring = h3.grid_disk(current_h3, k)
            local = [c for c in ring if c in valid_set]
            if len(local) >= 50:
                break

    if not local:
        origin, ev_name = demand.choose_h3(current_time, "origin")
        dist = h3.grid_distance(current_h3, origin)
        return origin, ev_name, dist

    best, extra = demand.local_weights(current_time, "origin")
    weights = [1.0 + float(extra.get(c, 0.0)) for c in local]
    origin = random.choices(local, weights=weights, k=1)[0]
    ev_name = best.get(origin, (None, 0.0))[0]
    dist = h3.grid_distance(current_h3, origin)
    return origin, ev_name, dist

"""def choose_destination_local(origin_h3: str,
                            current_time: datetime,
                            demand: DemandModel,
                            dest_cache: H3DiskCache,
                            valid_set: set[str]) -> tuple[str, str|None, int]:
    disk = dest_cache.disk(origin_h3)
    local = [c for c in disk if c in valid_set]
    if not local:
        dest, ev_name = demand.choose_h3(current_time, "destination")
        dist = h3.grid_distance(origin_h3, dest)
        return dest, ev_name, dist
    # opcional: ponderar destination por eventos também
    best, extra = demand.local_weights(current_time, "destination")
    weights = [1.0 + float(extra.get(c, 0.0)) for c in local]
    dest = random.choices(local, weights=weights, k=1)[0]
    ev_name = best.get(dest, (None, 0.0))[0]
    dist = h3.grid_distance(origin_h3, dest)
    return dest, ev_name, dist"""

def choose_destination_local(
          origin_h3: str,
          current_time: datetime,
          demand: DemandModel,
          dest_cache: H3DiskCache | None,   # <- permite None
          valid_set: set[str],
      ) -> tuple[str, str | None, int]:

    # --- melhoria cirúrgica: só usa cache se existir ---
    if dest_cache is not None:
        disk = dest_cache.disk(origin_h3)
        local = [c for c in disk if c in valid_set]
    else:
        local = []  # sem cache/local, usa fallback global

    if not local:
        dest, ev_name = demand.choose_h3(current_time, "destination")
        dist = h3.grid_distance(origin_h3, dest)
        return dest, ev_name, dist

    # opcional: ponderar destination por eventos também
    best, extra = demand.local_weights(current_time, "destination")
    weights = [1.0 + float(extra.get(c, 0.0)) for c in local]
    dest = random.choices(local, weights=weights, k=1)[0]
    ev_name = best.get(dest, (None, 0.0))[0]
    dist = h3.grid_distance(origin_h3, dest)
    return dest, ev_name, dist

# ============================================================
# 7) Sink Parquet por corrida
# ============================================================
TRIP_SCHEMA = pa.schema([
    ("date", pa.string()),
    ("driver_bucket", pa.int32()),
    ("trip_id", pa.int64()),
    ("driver_id", pa.int32()),
    ("trip_seq", pa.int32()),
    ("request_ts", pa.int64()),
    ("pickup_time_min", pa.float32()),
    ("trip_time_min", pa.float32()),
    ("origin_h3", pa.string()),
    ("destination_h3", pa.string()),
    ("h3_distance_to_call", pa.int32()),
    ("event_name", pa.string()),
    ("weekday", pa.int8()),
    ("hour", pa.int8()),
])

AGG_SCHEMA = pa.schema([
    ("date", pa.string()),
    ("h3_index", pa.string()),
    ("state", pa.string()),
    ("n_trips", pa.int32()),
    ("n_drivers", pa.int32()),
    ("avg_pickup_time", pa.float32()),
    ("avg_trip_time", pa.float32()),
    ("event_exposed_ratio", pa.float32()),
])


def driver_bucket_int(driver_id: int, bucket_size: int = 1000) -> int:
    return int(driver_id // bucket_size)

class TripParquetSink:
    """Sink Parquet com **RAM estável**.

    Mudança crítica: não usamos mais `list[dict]` (muito caro em Python e explode RAM).
    Em vez disso, mantemos buffers **colunares** (listas por coluna) e geramos Arrow Table no flush.
    """
    def __init__(self, out_dir: str, flush_rows: int = 25_000):
        self.out_dir = out_dir
        os.makedirs(out_dir, exist_ok=True)
        self.flush_rows = int(flush_rows)

        # buffers colunares na ordem do schema
        self._col_names = [f.name for f in TRIP_SCHEMA]
        self.cols = {name: [] for name in self._col_names}

        self.part = 0

    def add(self, row: dict):
        # append por coluna (bem mais leve do que dict por linha)
        for name in self._col_names:
            self.cols[name].append(row[name])

        # flush por tamanho de qualquer coluna (todas têm mesmo tamanho)
        if len(self.cols[self._col_names[0]]) >= self.flush_rows:
            self.flush()

    def flush(self):
        n = len(self.cols[self._col_names[0]])
        if n == 0:
            return

        # Constrói Table sem inferência (schema fixo)
        table = pa.table(self.cols, schema=TRIP_SCHEMA)
        path = f"{self.out_dir}/part-{self.part:05d}.parquet"
        pq.write_table(table, path, compression="zstd", use_dictionary=True, write_statistics=True)

        self.part += 1

        # limpa buffers
        for name in self._col_names:
            self.cols[name].clear()

    def flush_all(self):
        self.flush()

    def flush_day(self, date_str: str):
      """
      Flush + close apenas das partições referentes a date_str.
      Isso evita crescimento de RAM ao longo dos dias.
      """
      # Coleta chaves que pertencem ao dia
      to_flush = []
      for key in list(self._writers.keys()):
          # key pode ser string com path ou tupla com date_str na posição 0
          if isinstance(key, str):
              if f"date={date_str}" in key or key.startswith(date_str) or (date_str in key):
                  to_flush.append(key)
          else:
              # tupla/list: tente achar date_str em qualquer item
              if any((isinstance(x, str) and x == date_str) or (isinstance(x, str) and f"date={date_str}" in x) for x in key):
                  to_flush.append(key)

      # Flush/close e remove do dicionário (libera memória!)
      for key in to_flush:
          w = self._writers.pop(key, None)
          if w is None:
              continue

          # Seu writer pode ter flush()/close() ou flush_all()
          if hasattr(w, "flush"):
              w.flush()
          if hasattr(w, "close"):
              w.close()
          elif hasattr(w, "flush_all"):
              w.flush_all()

# ============================================================
# 8) Simulação por batch
# ============================================================
def empty_aggregate():
    return {"n_trips": 0, "pickup_sum": 0.0, "pickup_n": 0, "trip_sum": 0.0, "trip_n": 0, "event_exposed": 0}

def simulate_driver_batch(args):
    #log_worker("Iniciando batch")
    drivers_batch, valid_h3s, valid_set, events, batch_id = args

    demand = DemandModel(valid_h3s, events)
    origin_cache = H3DiskCache(CALL_MAX_DIST)
    dest_cache   = H3DiskCache(DEST_MAX_DIST)
    # agregados por DIA (para RAM estável)

    trips_out_dir = f"{TRIPS_DIR}/_staging/batch={batch_id:03d}"
    sink = TripParquetSink(trips_out_dir, flush_rows=25_000)

    day = START_DATE
    trip_global_id = 0

    while day < END_DATE:
        weekday = day.weekday()
        work_p = WORK_PROBABILITY[weekday]
        date_str = day.date().isoformat()

        aggregates = defaultdict(empty_aggregate)

        ##LOG DE ATRIBUIÇÕES##
        day_trips = 0
        day_assigned_fail = 0
        day_idle_spent = 0.0
        day_pickup = 0.0
        day_trip = 0.0

        for drv in drivers_batch:
            if random.random() > work_p:
                continue

            # mantém parecido com o anterior
            #ORIGINAL: work_limit = drv["daily_minutes"] if random.random() < 0.75 else random.uniform(10, 14) * 60.0

            #ALTERAÇÃO PARA MANTER WORKLIMIT EM MINUTOS
            work_limit = float(drv["daily_minutes"])

            # proteção contra unidade errada (se vier em horas)
            if work_limit <= 24:         # 10, 12, 14 etc.
                work_limit *= 60.0       # converte pra minutos

            # proteção contra valores absurdos baixos
            work_limit = max(work_limit, 480.0)  # mínimo 8h
            work_limit *= random.uniform(0.9, 1.1)

            worked = 0.0
            seq = 0

            #if seq == 0:  # só no começo do dia do motorista
              #print("driver", drv["driver_id_int"], "work_limit(min)", work_limit)
            #FIM DA ALTERAÇÃO PARA MANTER WORKLIMIT EM MINUTOS



            current_time = day + timedelta(hours=random.uniform(SHIFT_START_HOUR_MIN, SHIFT_START_HOUR_MAX))
            current_h3 = drv["home_h3"]
            #print("DEBUG enter while:", "worked=", worked, "work_limit=", work_limit)
            driver_trips = 0
            driver_idle_spent = 0.0
            driver_fail_blocks = 0

            stats = {
              "in_window_steps": 0,     # quantos steps tiveram janela ativa
              "sampled_event": 0,       # quantas tentativas sortearam um evento (ev_origin != None)
              "background": 0,          # quantas tentativas caíram no background com janela ativa
              "accepted": 0,            # quantas aceitaram
              "rejected": 0,            # quantas rejeitaram (mesmo tendo ev)
            }
            while worked < work_limit:
                #print("DEBUG inside while (should appear at least once)")
                idle_min = TimeModel.idle_time_minutes(weekday)
                idle_elapsed = 0.0
                assigned = False
                origin = None
                ev_origin = None
                dist_call = 0

                while idle_elapsed < idle_min:
                    for _ in range(int(CALLS_PER_IDLE_STEP)):
                        best_map, extra_map = demand.local_weights(current_time, "origin")
                        in_window = bool(extra_map)

                        if in_window:
                            stats["in_window_steps"] += 1
                        origin, ev_origin, dist_call = choose_origin_local(
                            current_h3=current_h3,
                            current_time=current_time,
                            demand=demand,
                            #disk_cache=origin_cache,
                            disk_cache=None,   # <-- DESLIGA
                            valid_set=valid_set,
                        )

                        if in_window:
                          if ev_origin:
                              stats["sampled_event"] += 1
                          else:
                              stats["background"] += 1

                        dist_eff = min(dist_call, CALL_MAX_DIST)
                        p = float(call_probability(dist_eff))
                        accepted = (random.random() < p)

                        if in_window and ev_origin:
                            if accepted:
                                stats["accepted"] += 1
                            else:
                                stats["rejected"] += 1

                        dist_eff = min(dist_call, CALL_MAX_DIST)  # <- decisão não “morre” por distância absurda
                        if random.random() < call_probability(dist_eff):
                            assigned = True
                            break
                    if assigned:
                        driver_trips += 1
                        #sink.add(row)
                        break

                    step = min(IDLE_STEP_MINUTES, idle_min - idle_elapsed)
                    idle_elapsed += step
                    current_time += timedelta(minutes=step)

                if not assigned:
                    worked += idle_elapsed
                    driver_idle_spent += idle_elapsed
                    driver_fail_blocks += 1
                    continue

                pickup_time = TimeModel.travel_time_minutes(dist_call)

                dest, ev_dest, dist_trip = choose_destination_local(
                    origin_h3=origin,
                    current_time=current_time,
                    demand=demand,
                    #dest_cache=dest_cache,
                    dest_cache=None,   # <-- DESLIGA
                    valid_set=valid_set,
                )
                trip_time = TimeModel.travel_time_minutes(dist_trip)

                key = (date_str, origin, "WithPassenger")
                agg = aggregates[key]
                agg["n_trips"] += 1
                agg["pickup_sum"] += pickup_time
                agg["pickup_n"] += 1
                agg["trip_sum"] += trip_time
                agg["trip_n"] += 1
                ev_name = ev_origin or ev_dest
                if ev_name:
                    agg["event_exposed"] += 1

                driver_id_int = drv["driver_id_int"]
                row = {
                    "date": date_str,
                    "driver_bucket": driver_bucket_int(driver_id_int),
                    "trip_id": int(trip_global_id),
                    "driver_id": int(driver_id_int),
                    "trip_seq": int(seq),
                    "request_ts": int(current_time.timestamp()),
                    "pickup_time_min": float(pickup_time),
                    "trip_time_min": float(trip_time),
                    "origin_h3": origin,
                    "destination_h3": dest,
                    "h3_distance_to_call": int(max(0, min(65535, dist_call))),
                    "event_name": ev_name or "",
                    "weekday": int(weekday),
                    "hour": int(current_time.hour),
                }
                sink.add(row)
                trip_global_id += 1
                #if trip_global_id % 1_000 == 0:
                  #print("disk_cache is None?", origin_cache is None)
                  #print("origin", origin, "dist_call", dist_call, "CALL_MAX_DIST", CALL_MAX_DIST, "p", call_probability(dist_call))

                worked += pickup_time + trip_time
                current_time += timedelta(minutes=pickup_time + trip_time)
                current_h3 = dest

                seq += 1

            """print(date_str, "driver", drv["driver_id_int"],
              "trips", driver_trips,
              "idle_spent(min)", round(driver_idle_spent, 1),
              "fail_blocks", driver_fail_blocks)  """
        # --- FLUSH agregados do dia (evita crescimento de RAM com número de dias) ---
        if aggregates:
            agg_rows = []
            for (dstr, h3_idx, state), agg in aggregates.items():
                agg_rows.append({
                    "date": dstr,
                    "h3_index": h3_idx,
                    "state": state,
                    "n_trips": int(agg["n_trips"]),
                    "n_drivers": None,
                    "avg_pickup_time": float(agg["pickup_sum"] / max(1, agg["pickup_n"])),
                    "avg_trip_time": float(agg["trip_sum"] / max(1, agg["trip_n"])),
                    "event_exposed_ratio": float(agg["event_exposed"] / max(1, agg["n_trips"])),
                })

            if agg_rows:
                agg_table = pa.Table.from_pylist(agg_rows, schema=AGG_SCHEMA)
                month = day.month
                agg_out_dir = f"{AGG_DIR}/year={day.year}/month={month:02d}/date={date_str}/batch={batch_id:03d}"
                os.makedirs(agg_out_dir, exist_ok=True)
                agg_path = f"{agg_out_dir}/part.parquet"
                pq.write_table(agg_table, agg_path, compression="zstd")

        aggregates.clear()
        sink.flush_day(date_str)   # novo: flush/close tudo daquela data
        gc.collect()
        """if day_trips > 0:
            print(date_str,
                  "trips", day_trips,
                  "idle_spent(min)", round(day_idle_spent, 1),
                  "fail_blocks", day_assigned_fail,
                  "avg_pickup", round(day_pickup/day_trips, 2),
                  "avg_trip", round(day_trip/day_trips, 2))
        else:
            print(date_str, "trips 0", "idle_spent(min)", round(day_idle_spent, 1), "fail_blocks", day_assigned_fail)"""
        day += timedelta(days=1)
        print("STATS", stats)
        if stats["sampled_event"] > 0:
            print("accept_rate_given_event =", stats["accepted"] / stats["sampled_event"])
        if (stats["background"] + stats["sampled_event"]) > 0:
            print("event_sampling_rate_in_window =", stats["sampled_event"] / (stats["background"] + stats["sampled_event"]))
        mem(f"Fim {day}")

    sink.flush_all()
    log_worker(f"Drivers processados: {len(drivers)}")


    # agregados já foram persistidos por dia acima

# ============================================================
# 9) Motoristas
# ============================================================
homes = random.choices(valid_h3s, k=TOTAL_DRIVERS)
drivers = []
for i in range(TOTAL_DRIVERS):
    daily_minutes = random.uniform(9, 11) * 60.0  # 9–11h ajuda a ficar perto de 30/dia
    drivers.append({
        "driver_id_int": i,
        "home_h3": homes[i],
        "daily_minutes": daily_minutes
    })
    #print(f'Daily minutes: {daily_minutes}')
print("drivers:", len(drivers))

# ============================================================
# 10) Eventos
# ============================================================
def H3LocalToList(df):
    return df["h3_index"].tolist()

def MontaDatasetDeH3Validos(h3_local_list, valid_set):
    out = []
    for h in h3_local_list:
        if h in valid_set:
            out.append(h)
    return out

events = []

df_air_h3 = pd.read_csv("/content/Aeroporto_Salgado_Filho_h3_res12.csv")
airport_h3_local = H3LocalToList(df_air_h3)
airport_h3_valid = MontaDatasetDeH3Validos(airport_h3_local, valid_set)

voos = pd.read_csv("/content/03_voos_atrasados_sbpa.csv", sep=";")
df_out = voos[voos["STATUS_ATRASO"] != "Desconhecido / Cancelado"].copy()
df_out["CHEGADA_REAL"] = pd.to_datetime(df_out["CHEGADA_REAL"], errors="coerce")

for _, r in df_out.iterrows():
    t0 = r["CHEGADA_REAL"]
    if pd.isna(t0):
        continue
    t1 = t0 + pd.Timedelta(hours=1)
    events.append(Event(
        name="Aeroporto Salgado Filho Voo Atrasado- SBPA",
        start=int(t0.timestamp() * 1000),
        end=int(t1.timestamp() * 1000),
        affected_h3s=airport_h3_valid,
        apply_to="origin",
        weight=350
    ))

DF_WEATHER = pd.read_csv("/content/dados_meteorologicos_utci_horario.csv")
"""AIRPORT_H3S = {
    '86a901287ffffff','86a90128fffffff','86a90129fffffff','86a90e937ffffff',
    '86a90166fffffff','86a901297ffffff','86a9012afffffff','86a9012a7ffffff',
    '86a9012b7ffffff','86a901667ffffff','86a90174fffffff','86a90e907ffffff',
    '86a90e92fffffff','86a9012d7ffffff','86a90164fffffff','86a90e917ffffff',
    '86a90e927ffffff'
}"""
AIRPORT_H3S = {'85a90e93fffffff', '85a9012bfffffff'}
DF_WEATHER["IS_AIRPORT"] = DF_WEATHER["INDEX_H3"].isin(AIRPORT_H3S)
print(DF_WEATHER["IS_AIRPORT"])
W = DF_WEATHER.loc[DF_WEATHER["IS_AIRPORT"]].copy()
W["time"] = pd.to_datetime(W["time"])
#W["time_utc"] = W["time"].dt.tz_convert("UTC")


def add_weather_events(df, sev, base_w=350):
    for _, r in df.iterrows():
        t0 = r["time"]
        t1 = t0 + pd.Timedelta(hours=1)
        events.append(Event(
            name=f"Aeroporto Salgado Filho Weather Severidade {sev}",
            #start=t0, end=t1,
            start=int(t0.timestamp() * 1000),
            end=int(t1.timestamp() * 1000),
            affected_h3s=airport_h3_valid,
            apply_to="origin",
            weight=base_w * sev
        ))

add_weather_events(W[W["utci_stress_category"].isin(["slight cold stress"])], 4)
add_weather_events(W[W["utci_stress_category"].isin(["moderate cold stress","moderate heat stress"])], 5)
add_weather_events(W[W["utci_stress_category"].isin(["strong cold stress","strong heat stress"])], 6)
add_weather_events(W[W["utci_stress_category"].isin(["very strong cold stress","very strong heat stress"])], 7)

print("events:", len(events))

# =========================
# SANITY CHECK DE EVENTOS
# =========================
from datetime import timezone

sim_start = START_DATE.replace(tzinfo=timezone.utc) if START_DATE.tzinfo is None else START_DATE
sim_end   = END_DATE.replace(tzinfo=timezone.utc)   if END_DATE.tzinfo is None   else END_DATE

print("SIM:", sim_start, "->", sim_end)
print("events_total:", len(events))
print("airport_h3_valid:", len(airport_h3_valid), " (se for 0, NUNCA terá evento)")

if events:
    ev_starts = [e.start for e in events]
    ev_ends   = [e.end   for e in events]
    print("events_min_start:", min(ev_starts))
    print("events_max_end  :", max(ev_ends))

    #in_window = [e for e in events if (e.end > sim_start and e.start < sim_end)]
    #print("events_in_sim_window:", len(in_window))

    sim_start_ms = int(sim_start.timestamp() * 1000)
    sim_end_ms   = int(sim_end.timestamp() * 1000)

    in_window = [e for e in events if (e.end > sim_start_ms and e.start < sim_end_ms)]

    # por tipo (nome)
    from collections import Counter
    c = Counter([e.name for e in in_window])
    print("top event names in window:", c.most_common(10))
else:
    print("WARNING: events list está vazia.")

# ============================================================
# 11) Runner paralelo (Colab)
# ============================================================
def run_simulation_parallel(valid_h3s, valid_set, drivers, events, n_workers=None):
    n_workers = n_workers or os.cpu_count() or 2
    batches = np.array_split(drivers, n_workers)
    args = [(list(b), valid_h3s, valid_set, events, i) for i, b in enumerate(batches)]
    with Pool(processes=n_workers) as pool:
        for _ in pool.imap_unordered(simulate_driver_batch, args, chunksize=1):
            pass

from datetime import datetime, timezone, timedelta

DAY = datetime(2025, 1, 2, tzinfo=timezone.utc)

day_start = DAY
day_end   = DAY + timedelta(days=1)

# converter para ms
day_start_ms = int(day_start.timestamp() * 1000)
day_end_ms   = int(day_end.timestamp() * 1000)

contador = 0

for ev in events:
    if (ev.start < day_end_ms) and (ev.end > day_start_ms):

        print(
            f"Evento: {ev.name}\n"
            f"Começo: {datetime.fromtimestamp(ev.start/1000, tz=timezone.utc)} - "
            f"Fim: {datetime.fromtimestamp(ev.end/1000, tz=timezone.utc)}\n"
        )

        contador += 1

print(f'Total de eventos para o dia {DAY}: {contador}')

# ============================================================
# 12) Start
# ============================================================
print("CPUs:", os.cpu_count())
print("Running")

# --- CORREÇÃO DO ERRO ---
# Sobrescrevemos o método flush_day problemático para usar o flush() padrão
# já que a nova implementação não usa mais self._writers
def patched_flush_day(self, date_str: str):
    self.flush()
TripParquetSink.flush_day = patched_flush_day
# ------------------------

run_simulation_parallel(valid_h3s=valid_h3s, valid_set=valid_set, drivers=drivers, events=events, n_workers=os.cpu_count())

# ============================================================
# 13) Mover resultados para Drive
# ============================================================
source_dir = "/content/generated_data/outputs_simulation_v6_FINAL"
drive_target_dir = "/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/outputs_simulation_V6_7"

os.makedirs(drive_target_dir, exist_ok=True)

print(f"Moving contents from '{source_dir}' to '{drive_target_dir}'...")
for item_name in os.listdir(source_dir):
    source_item_path = os.path.join(source_dir, item_name)
    destination_item_path = os.path.join(drive_target_dir, item_name)

    if os.path.exists(destination_item_path):
        if os.path.isdir(destination_item_path):
            shutil.rmtree(destination_item_path)
        else:
            os.remove(destination_item_path)

    shutil.move(source_item_path, drive_target_dir)

if os.path.exists(source_dir):
    shutil.rmtree(source_dir)
print("Content move complete.")

def get_folder_size(filepath, unit='MB'):
    total_size = 0
    if not os.path.exists(filepath):
        return 0.0
    for dirpath, dirnames, filenames in os.walk(filepath):
        for f in filenames:
            fp = os.path.join(dirpath, f)
            if not os.path.islink(fp):
                total_size += os.path.getsize(fp)
    if unit == 'KB':
        return total_size / 1024
    elif unit == 'MB':
        return total_size / (1024 * 1024)
    elif unit == 'GB':
        return total_size / (1024 * 1024 * 1024)
    else:
        return total_size

print(f"The size of the target folder '{drive_target_dir}' is: {get_folder_size(drive_target_dir, unit='MB'):.2f} MB")

#Valida se está gerando evento

!pip -q install pyarrow pandas

import pyarrow.dataset as ds
import pyarrow.compute as pc

TRIPS_ROOT = "/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/outputs_simulation_V6/trips_log/_staging"
#DAY = "2025-01-02"
DAY = "2025-04-01"

AIRPORT_H3S = {
    '86a901287ffffff','86a90128fffffff','86a90129fffffff','86a90e937ffffff',
    '86a90166fffffff','86a901297ffffff','86a9012afffffff','86a9012a7ffffff',
    '86a9012b7ffffff','86a901667ffffff','86a90174fffffff','86a90e907ffffff',
    '86a90e92fffffff','86a9012d7ffffff','86a90164fffffff','86a90e917ffffff',
    '86a90e927ffffff'
}

dset = ds.dataset(TRIPS_ROOT, format="parquet", partitioning="hive")

# Lê apenas driver_id do dia desejado
table = dset.to_table(
    #columns=["driver_id"],
    #filter=(pc.field("date") == DAY)#&
    filter=(pc.field("origin_h3").isin(airport_h3_valid) |
    pc.field("destination_h3").isin(airport_h3_valid)) &
            (pc.match_substring(pc.field("event_name"), "Voo Atrasado"))

)

# Pega somente as 20 primeiras linhas
df_20 = table.slice(0, 20).to_pandas()
#df_20 = table.to_pandas()

df_20

from google.colab import drive
drive.mount('/content/drive')

!pip -q install pyarrow pandas

import pyarrow.dataset as ds
import pyarrow.compute as pc

TRIPS_ROOT = "/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/outputs_simulation_V6/trips_log/_staging"

dset = ds.dataset(
    TRIPS_ROOT,
    format="parquet",
    partitioning="hive"
)

# Filtro robusto:
# event_name NOT NULL
# event_name NOT EMPTY
filter_expr = (
    pc.field("event_name").is_valid() #&
    #(pc.utf8_trim_whitespace(pc.field("event_name")) != "")
)

# Lê apenas destination_h3
table = dset.to_table(
    columns=["destination_h3"],
    filter=filter_expr
)

# Remove destination_h3 nulos
table = table.filter(pc.field("destination_h3").is_valid())

# Distintos
distinct_dest = (
    table
    .group_by(["destination_h3"])
    .aggregate([])
)

# Converte para pandas
df_distinct_dest = distinct_dest.to_pandas()

df_distinct_dest

table = dset.to_table(
    filter=(pc.field("date") == DAY),
)

df_day = table.to_pandas()

df_counts = (
    df_day.groupby("driver_id", as_index=False)
    .size()
    .rename(columns={"size": "n_trips"})
    .sort_values("n_trips", ascending=False)
)

print("Resumo por motorista:")
print(df_counts)

print("\nTodas as corridas do dia:")
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
display(df_day)

import pyarrow.dataset as ds
import pyarrow.compute as pc

TRIPS_ROOT = "/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/outputs_simulation_V6/trips_log/_staging"

dset = ds.dataset(TRIPS_ROOT, format="parquet", partitioning="hive")

# Lê apenas date e driver_id
table = dset.to_table(columns=["date", "driver_id"])

# Primeiro remove duplicatas (date, driver_id)
distinct = (
    table
    .group_by(["date", "driver_id"])
    .aggregate([])
)

# Agora conta quantos drivers por dia
drivers_per_day = (
    distinct
    .group_by(["date"])
    .aggregate([("driver_id", "count")])
)

drivers_per_day_df = drivers_per_day.to_pandas().sort_values("date")

drivers_per_day_df

#Média por dia
drivers_per_day_df["driver_id_count"].mean()

import pyarrow.dataset as ds
import pyarrow.compute as pc
import pandas as pd

TRIPS_ROOT = "/content/drive/MyDrive/DOUTORADO/003_DADOS_SINTETICOS/outputs_simulation_V6/trips_log/_staging"

dset = ds.dataset(TRIPS_ROOT, format="parquet", partitioning="hive")

# Lê apenas o necessário
table = dset.to_table(columns=["date", "driver_id"])

# 1) Corridas por motorista por dia (conta de linhas)
trips_per_driver_day = (
    table
    .group_by(["date", "driver_id"])
    .aggregate([("driver_id", "count")])   # conta linhas no grupo
    .rename_columns(["date", "driver_id", "n_trips"])
)

trips_per_driver_day_df = trips_per_driver_day.to_pandas()
trips_per_driver_day_df["date"] = pd.to_datetime(trips_per_driver_day_df["date"])
trips_per_driver_day_df = trips_per_driver_day_df.sort_values(["date", "driver_id"])

# 2) Média de corridas/dia por motorista (média nos dias em que ele trabalhou/apareceu)
avg_trips_per_driver_df = (
    trips_per_driver_day_df
    .groupby("driver_id", as_index=False)["n_trips"]
    .mean()
    .rename(columns={"n_trips": "avg_trips_per_day"})
    .sort_values("avg_trips_per_day", ascending=False)
)

# 3) Média de corridas por motorista naquele dia (média entre motoristas do dia)
avg_trips_per_day_df = (
    trips_per_driver_day_df
    .groupby("date", as_index=False)["n_trips"]
    .mean()
    .rename(columns={"n_trips": "avg_trips_per_driver_that_day"})
    .sort_values("date")
)

# 4) Média global (todas as observações dia-motorista)
overall_avg = trips_per_driver_day_df["n_trips"].mean()

print("Média global de corridas por motorista por dia:", overall_avg)

# Outputs principais
trips_per_driver_day_df.head(20), avg_trips_per_driver_df.head(20), avg_trips_per_day_df.head(20)

voos = pd.read_csv("/content/03_voos_atrasados_sbpa.csv", sep=";")
df_out = voos[voos["outlier_chegada"] != "Desconhecido / Cancelado"].copy()
df_out["CHEGADA_REAL"] = pd.to_datetime(df_out["CHEGADA_REAL"], errors="coerce")

for _, r in df_out.iterrows():
    t0 = r["CHEGADA_REAL"]
    if pd.isna(t0):
        continue
    t1 = t0 + pd.Timedelta(hours=1)
    events.append(Event(
        name="Aeroporto Salgado Filho Voo Atrasado- SBPA",
        start=int(t0.timestamp() * 1000),
        end=int(t1.timestamp() * 1000),
        affected_h3s=airport_h3_valid,
        apply_to="origin",
        weight=150
    ))

⚠️ **Aviso:** O código de liberação de memória não deve ser rodado isoladamente aqui. Ele deve ser inserido (descomentado) no final do loop diário da função `simulate_driver_batch` localizada na célula principal de simulação.